import JointVentureForm from '../components/JointVentureForm';

export default function JointVenturePage(){return <main className="publicShell">
  <nav className="publicNav"><a className="publicBrand" href="/">SAHJONY<small>REAL ESTATE OPERATIONS</small></a><div className="publicLinks"><a href="/sell">Sell a Property</a><a href="/buyers">Cash Buyers</a><a href="/joint-venture">Joint Venture</a><a href="/partners">Partners</a><a href="/contact">Contact</a><a className="loginPill" href="/owner-access">Owner Login</a></div></nav>
  <header className="publicPageHeader"><span className="sectionEyebrow">WHOLESALER JOINT VENTURES</span><h1>Have the deal. Need stronger disposition.</h1><p>SAHJONY reviews JV opportunities from wholesalers and direct deal sources nationwide. Bring a real opportunity; we can evaluate the economics, match buyer demand, coordinate disposition, and structure a written JV when the deal and responsibilities are clear.</p></header>
  <section className="publicSection"><span className="sectionEyebrow">JV OPERATING MODEL</span><h2>One deal. Defined roles. Documented split.</h2><div className="processGrid"><article className="processCard"><span className="processNumber">01 · SUBMIT</span><h3>Send the deal facts</h3><p>Property, contract status, seller or contract price, ARV, repairs, timeline, buyer status, and proposed split.</p></article><article className="processCard"><span className="processNumber">02 · VERIFY</span><h3>Underwrite and confirm authority</h3><p>SAHJONY verifies economics, assignment/JV rights, title path, and buyer coverage before marketing or making commitments.</p></article><article className="processCard"><span className="processNumber">03 · EXECUTE</span><h3>Disposition under written terms</h3><p>Approved opportunities move under a written JV agreement defining responsibilities, compensation, buyer handling, and closing instructions.</p></article></div></section>
  <section className="intakeWrap"><JointVentureForm/><p className="publicNote">Submission alone does not create a joint venture, partnership, agency relationship, assignment, brokerage relationship, or right to compensation. SAHJONY must review the transaction and execute separate written terms before joint marketing or compensation is authorized.</p></section>
  <footer className="publicFooter"><span>© 2026 SAHJONY CAPITAL LLC. Real estate investment operations.</span><span><a className="backLink" href="/partners">Other partnerships</a> · <a className="backLink" href="/contact">Contact</a></span></footer>
</main>}
