'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import styles from '../owner.module.css';

const API_URL = 'https://backend-pi-opal-65.vercel.app';
const SESSION_STORAGE = 'sahjony_owner_session';
const SIGN_IN_URL = '/owner-access';

type Deal={id:number;stage:string;target_contract_price?:number;target_buyer_price?:number;projected_assignment_fee?:number;next_action?:string};
type Buyer={id:number;name:string;company?:string;buyer_type:string;email?:string;phone:string;proof_of_funds_verified:boolean;reliability_score:number;closing_days:number};
type Match={id:number;deal_id:number;buyer_id:number;buyer_name:string;score:number;reasons:string[];status:string};
type Offer={id:number;deal_id:number;buyer_id:number;buyer_name:string;amount:number;earnest_money?:number;closing_days?:number;proof_of_funds_status:string;contingencies:string[];status:string;ranking_score:number;submitted_at:string};
type Campaign={id:number;deal_id:number;name:string;status:string;asking_price?:number;audience_count:number;sent_count:number;response_count:number};
type Selection={id:number;deal_id:number;buyer_id:number;buyer_offer_id:number;assignment_price:number;assignment_fee:number;status:string;approval_id?:number};
type Snapshot={deals:Deal[];buyers:Buyer[];matches:Match[];offers:Offer[];campaigns:Campaign[];selections:Selection[]};
const empty:Snapshot={deals:[],buyers:[],matches:[],offers:[],campaigns:[],selections:[]};
function money(v?:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v||0)}

export default function DispositionCenter(){
 const[token,setToken]=useState(''); const[data,setData]=useState<Snapshot>(empty); const[dealId,setDealId]=useState<number|null>(null); const[loading,setLoading]=useState(true); const[authenticated,setAuthenticated]=useState(false); const[notice,setNotice]=useState(''); const[error,setError]=useState(''); const[approvalMap,setApprovalMap]=useState<Record<number,number>>({});
 const selectedDeal=useMemo(()=>data.deals.find(d=>d.id===dealId)||data.deals[0],[data.deals,dealId]);
 const dealMatches=useMemo(()=>data.matches.filter(m=>m.deal_id===selectedDeal?.id),[data.matches,selectedDeal]);
 const dealOffers=useMemo(()=>data.offers.filter(o=>o.deal_id===selectedDeal?.id),[data.offers,selectedDeal]);
 const request=useCallback(async(path:string,options:RequestInit={},override?:string)=>{const active=override||token;if(!active){window.location.replace(SIGN_IN_URL);throw new Error('Owner session required');}const r=await fetch(`${API_URL}${path}`,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${active}`,...(options.headers||{})}});const body=await r.json().catch(()=>({}));if(r.status===401||r.status===403){localStorage.removeItem(SESSION_STORAGE);window.location.replace(SIGN_IN_URL);throw new Error('Owner session expired');}if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:`Request failed (${r.status})`);return body},[token]);
 const load=useCallback(async(override?:string)=>{setLoading(true);setError('');try{const body=await request('/disposition/snapshot',{},override);setData(body);setAuthenticated(true);if(!dealId&&body.deals?.length)setDealId(body.deals[0].id);}catch(e){setError(e instanceof Error?e.message:'Unable to load disposition center')}finally{setLoading(false)}},[request,dealId]);
 useEffect(()=>{const stored=localStorage.getItem(SESSION_STORAGE)||'';if(!stored){location.replace(SIGN_IN_URL);return}setToken(stored);void load(stored)},[load]);
 async function match(){if(!selectedDeal)return;setLoading(true);setError('');try{const r=await request(`/disposition/deals/${selectedDeal.id}/match-buyers`,{method:'POST',body:'{}'});setNotice(`Ranked ${r.matches.length} buyers.`);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to match buyers')}finally{setLoading(false)}}
 async function campaign(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedDeal)return;const f=new FormData(e.currentTarget);setLoading(true);setError('');try{const r=await request(`/disposition/deals/${selectedDeal.id}/campaigns`,{method:'POST',body:JSON.stringify({name:f.get('name'),asking_price:Number(f.get('asking_price')||0),minimum_assignment_fee:Number(f.get('minimum_assignment_fee')||0),minimum_match_score:Number(f.get('minimum_match_score')||50),channels:['email','sms']})});setApprovalMap(m=>({...m,[r.campaign_id]:r.approval_id}));setNotice(`Campaign #${r.campaign_id} prepared for ${r.audience_count} buyers; owner approval required.`);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to prepare campaign')}finally{setLoading(false)}}
 async function offer(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedDeal)return;const f=new FormData(e.currentTarget);setLoading(true);setError('');try{const r=await request(`/disposition/deals/${selectedDeal.id}/offers`,{method:'POST',body:JSON.stringify({buyer_id:Number(f.get('buyer_id')),amount:Number(f.get('amount')),earnest_money:Number(f.get('earnest_money')||0),closing_days:Number(f.get('closing_days')||14),proof_of_funds_status:f.get('proof_of_funds_status'),proof_of_funds_reference:f.get('proof_of_funds_reference'),contingencies:String(f.get('contingencies')||'').split(',').map(x=>x.trim()).filter(Boolean),notes:f.get('notes')})});setNotice(`Offer recorded with ranking score ${r.ranking_score}.`);e.currentTarget.reset();await load()}catch(e){setError(e instanceof Error?e.message:'Unable to record offer')}finally{setLoading(false)}}
 async function selectOffer(id:number){setLoading(true);setError('');try{const r=await request(`/disposition/offers/${id}/select`,{method:'POST',body:'{}'});setApprovalMap(m=>({...m,[r.selection_id]:r.approval_id}));setNotice(`Selection #${r.selection_id} prepared; projected assignment fee ${money(r.assignment_fee)}. Approve in Control Plane, then finalize.`);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to select offer')}finally{setLoading(false)}}
 async function finalize(id:number){setLoading(true);setError('');try{const r=await request(`/disposition/selections/${id}/finalize`,{method:'POST',body:'{}'});setNotice(`Assignee finalized. Assignment fee ${money(r.assignment_fee)}.`);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to finalize selection')}finally{setLoading(false)}}
 if(!authenticated)return <main className={styles.setup}><section className={styles.setupCard}><span className={styles.eyebrow}>DISPOSITION</span><h1>{loading?'Checking owner session…':'Owner session required'}</h1><p>{error||'Redirecting to owner access.'}</p><a className={styles.linkButton} href={SIGN_IN_URL}>Owner access</a></section></main>;
 return <main className={styles.page}>
  <header className={styles.header}><div><span className={styles.eyebrow}>BUYER DISPOSITION</span><h1>Disposition Center</h1><p>Rank qualified buyers, collect offers, verify funds, and select the strongest assignee.</p></div><div className={styles.actions}><button onClick={()=>void load()} disabled={loading}>Refresh</button><a className={styles.linkButton} href="/owner/deals">Contracts</a><a className={styles.linkButton} href="/owner/closing">Closing</a><a className={styles.linkButton} href="/owner">Control Plane</a></div></header>
  {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.metrics}><article><span>Deals</span><strong>{data.deals.length}</strong></article><article><span>Tenant buyers</span><strong>{data.buyers.length}</strong></article><article><span>Matched buyers</span><strong>{dealMatches.length}</strong></article><article><span>Buyer offers</span><strong>{dealOffers.length}</strong></article><article><span>Selected assignments</span><strong>{data.selections.length}</strong></article></section>
  <section className={styles.grid}>
   <article className={styles.card}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>DEAL</span><h2>Buyer matching</h2></div><select value={selectedDeal?.id||''} onChange={e=>setDealId(Number(e.target.value))}>{data.deals.map(d=><option key={d.id} value={d.id}>Deal #{d.id} · {d.stage}</option>)}</select></div>{selectedDeal?<><p>Contract {money(selectedDeal.target_contract_price)} · Buyer target {money(selectedDeal.target_buyer_price)} · Fee {money(selectedDeal.projected_assignment_fee)}</p><button onClick={()=>void match()} disabled={loading}>Refresh buyer matches</button><div className={styles.list}>{dealMatches.map(m=><div key={m.id}><span><b>{m.buyer_name}</b><small>{m.reasons.join(' · ')||'No match reasons'}</small></span><strong>{Math.round(m.score)}</strong></div>)}</div></>:<p>No active deals available.</p>}</article>
   <article className={styles.card}><span className={styles.eyebrow}>CAMPAIGN</span><h2>Prepare buyer campaign</h2><form onSubmit={campaign} className={styles.activationForm}><input name="name" placeholder="Campaign name" defaultValue={selectedDeal?`Deal #${selectedDeal.id} buyer campaign`:''}/><label>Buyer asking price<input name="asking_price" type="number" defaultValue={selectedDeal?.target_buyer_price||''} required/></label><label>Minimum assignment fee<input name="minimum_assignment_fee" type="number" defaultValue={selectedDeal?.projected_assignment_fee||''}/></label><label>Minimum match score<input name="minimum_match_score" type="number" defaultValue="50"/></label><button disabled={loading||!selectedDeal}>Prepare approval-gated campaign</button><small>Street numbers remain hidden in public marketing. Campaign launch remains owner-approved.</small></form></article>
  </section>
  <section className={styles.grid}>
   <article className={styles.card}><span className={styles.eyebrow}>OFFER INTAKE</span><h2>Record buyer offer</h2><form onSubmit={offer} className={styles.activationForm}><select name="buyer_id" required><option value="">Select buyer</option>{data.buyers.map(b=><option key={b.id} value={b.id}>{b.name}{b.company?` · ${b.company}`:''}</option>)}</select><input name="amount" type="number" placeholder="Offer amount" required/><input name="earnest_money" type="number" placeholder="Buyer EMD"/><input name="closing_days" type="number" defaultValue="14"/><select name="proof_of_funds_status" defaultValue="missing"><option value="missing">POF missing</option><option value="pending">POF pending</option><option value="verified">POF verified</option></select><input name="proof_of_funds_reference" placeholder="POF reference"/><input name="contingencies" placeholder="Contingencies, comma separated"/><textarea name="notes" placeholder="Offer notes"/><button disabled={loading||!selectedDeal}>Record and rank offer</button></form></article>
   <article className={styles.card}><span className={styles.eyebrow}>RANKING</span><h2>Buyer offers</h2><div className={styles.list}>{dealOffers.length?dealOffers.map(o=><div key={o.id}><span><b>{o.buyer_name} · {money(o.amount)}</b><small>Score {o.ranking_score} · POF {o.proof_of_funds_status} · {o.closing_days||'—'} days</small><small>{o.contingencies.length?`Contingencies: ${o.contingencies.join(', ')}`:'No contingencies recorded'}</small></span><button onClick={()=>void selectOffer(o.id)} disabled={loading||o.proof_of_funds_status!=='verified'||o.status==='selected'}>Select</button></div>):<p>No buyer offers recorded.</p>}</div></article>
  </section>
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>ASSIGNMENT CONTROL</span><h2>Pending and finalized selections</h2></div><strong>{data.selections.length}</strong></div><div className={styles.list}>{data.selections.length?data.selections.map(s=><div key={s.id}><span><b>Deal #{s.deal_id} · Buyer #{s.buyer_id}</b><small>{money(s.assignment_price)} assignment price · {money(s.assignment_fee)} fee · {s.status}</small><small>{s.approval_id?`Approval #${s.approval_id}`:'No approval linked'}</small></span><button onClick={()=>void finalize(s.id)} disabled={loading||s.status==='finalized'}>Finalize after approval</button></div>):<p>No assignee selected yet.</p>}</div></section>
 </main>
}
