'use client';

import { useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const API_URL = '/api/intelligence-platform';
const SESSION_STORAGE = 'sahjony_owner_session';

type Entity = { id:number; entity_type:string; entity_id:number; canonical_data:Record<string,unknown>; verification_status:string; confidence:number; conflict_count:number; source_count:number; updated_at:string };
type Snapshot = { generated_at:string; entity_count:number; fact_count:number; open_conflicts:number; entities:Entity[] };
const empty:Snapshot={generated_at:'',entity_count:0,fact_count:0,open_conflicts:0,entities:[]};

export default function IntelligenceCenter(){
  const [token,setToken]=useState(''); const [data,setData]=useState<Snapshot>(empty); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const request=useCallback(async(path:string,options:RequestInit={},override?:string)=>{const active=override||token;if(!active){location.replace('/owner-access');throw new Error('Owner session required');}const response=await fetch(`${API_URL}${path}`,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${active}`,...(options.headers||{})}});const text=await response.text();let body:any={};if(text){try{body=JSON.parse(text);}catch{body={detail:text};}}if(response.status===401||response.status===403){localStorage.removeItem(SESSION_STORAGE);location.replace('/owner-access');throw new Error('Owner session expired');}if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:`Request failed (${response.status})`);return body;},[token]);
  const load=useCallback(async(override?:string)=>{setLoading(true);setError('');try{setData(await request('/snapshot',{},override));}catch(e){setError(e instanceof Error?e.message:'Unable to load intelligence platform');}finally{setLoading(false);}},[request]);
  useEffect(()=>{const stored=localStorage.getItem(SESSION_STORAGE)||'';if(!stored){location.replace('/owner-access');return;}setToken(stored);void load(stored);},[load]);
  return <main className={styles.page}><header className={styles.header}><div><span className={styles.eyebrow}>ENTERPRISE DATA</span><h1>Intelligence Center</h1><p>Canonical property, seller, and buyer facts with source confidence and verification.</p></div><div className={styles.actions}><button onClick={()=>void load()} disabled={loading}>Refresh</button><a className={styles.linkButton} href="/owner/events">Events</a><a className={styles.linkButton} href="/owner">Control Plane</a></div></header>{error&&<div className={styles.error}>{error}</div>}<section className={styles.metrics}><article><span>Canonical entities</span><strong>{data.entity_count}</strong></article><article><span>Source facts</span><strong>{data.fact_count}</strong></article><article><span>Open conflicts</span><strong>{data.open_conflicts}</strong></article><article><span>Verified</span><strong>{data.entities.filter(e=>e.verification_status==='verified').length}</strong></article><article><span>Disputed</span><strong>{data.entities.filter(e=>e.verification_status==='disputed').length}</strong></article></section><section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>CANONICAL RECORDS</span><h2>Unified intelligence</h2></div><strong>{data.entities.length}</strong></div><div className={styles.list}>{data.entities.length?data.entities.map(entity=><div key={entity.id}><span><b>{entity.entity_type} #{entity.entity_id}</b><small>{entity.verification_status} · confidence {Math.round(entity.confidence)}% · {entity.source_count} sources · {entity.conflict_count} conflicts</small><small>{Object.entries(entity.canonical_data||{}).slice(0,4).map(([key,value])=>`${key}: ${String(value)}`).join(' · ')||'No canonical fields yet'}</small></span></div>):<p>No canonical intelligence records yet. ATTOM, BatchData, county verification, buyer activity, and seller workflows can now publish facts into this layer.</p>}</div></section></main>;
}
