export default function Home(){return <main className="publicShell">
  <nav className="publicNav"><a className="publicBrand" href="/">SAHJONY<small>REAL ESTATE OPERATIONS</small></a><div className="publicLinks"><a href="/sell">Sell a Property</a><a href="/buyers">Cash Buyers</a><a href="/joint-venture">Joint Venture</a><a href="/partners">Partners</a><a href="/contact">Contact</a><a className="loginPill" href="/owner-access">Owner Login</a></div></nav>
  <section className="heroPublic"><span className="heroEyebrow">PRIVATE CAPITAL · DIRECT REAL ESTATE</span><h1>Real estate problems need executable solutions.</h1><p>SAHJONY works directly with property owners, cash buyers, wholesalers, brokers, and closing partners to evaluate off-market real estate opportunities with clear terms, disciplined underwriting, and controlled execution.</p><div className="heroActions"><a className="primaryButton" href="/sell">Tell us about a property</a><a className="secondaryButton" href="/joint-venture">Submit a JV deal</a></div></section>
  <section className="publicSection"><span className="sectionEyebrow">ONE FRONT DOOR · FOUR PATHS</span><h2>Start with the role that fits you.</h2><p className="publicSectionIntro">Public submissions enter a controlled intake queue. Internal underwriting, title work, buyer data, negotiations, and operating controls remain private.</p><div className="audienceGrid">
    <article className="audienceCard"><span className="sectionEyebrow">OWNERS</span><h3>Sell a property</h3><p>Share the property, condition, timing, motivation, and price expectations. Acquisitions reviews the submission before any offer is discussed.</p><a href="/sell">Start seller intake →</a></article>
    <article className="audienceCard"><span className="sectionEyebrow">INVESTORS</span><h3>Cash Buyer Network</h3><p>Register your buying box, target ZIP codes, price range, rehab tolerance, and closing speed. Proof of funds is verified separately.</p><a href="/buyers">Register buying box →</a></article>
    <article className="audienceCard"><span className="sectionEyebrow">WHOLESALERS</span><h3>Joint Venture with SAHJONY</h3><p>Bring a real off-market opportunity and let SAHJONY evaluate buyer demand, disposition strategy, deal economics, and a written JV structure.</p><a href="/joint-venture">Submit a JV opportunity →</a></article>
    <article className="audienceCard"><span className="sectionEyebrow">PROFESSIONALS</span><h3>Partner with SAHJONY</h3><p>Agents, brokers, title companies, contractors, lenders, and other transaction professionals can route opportunities or partnership inquiries directly to Operations.</p><a href="/partners">Partner intake →</a></article>
  </div></section>
  <section className="publicSection"><span className="sectionEyebrow">JOINT VENTURE DISPOSITION</span><h2>Have the deal. Need the buyer network.</h2><p className="publicSectionIntro">JV opportunities are reviewed as transactions, not treated as automatically marketable inventory. We verify control, economics, title path, buyer demand, and the proposed compensation structure before joint execution.</p><div className="processGrid"><article className="processCard"><span className="processNumber">01 · DEAL CONTROL</span><h3>Verify the right to transact</h3><p>Confirm seller authority, assignable contract rights, deadlines, access, and any restrictions before disposition.</p></article><article className="processCard"><span className="processNumber">02 · BUYER MATCH</span><h3>Route to real demand</h3><p>Match the property against SAHJONY cash buyers by ZIP, price, rehab tolerance, closing speed, and POF status.</p></article><article className="processCard"><span className="processNumber">03 · WRITTEN JV</span><h3>Define the split before execution</h3><p>Responsibilities, marketing rights, buyer handling, compensation, and closing instructions are documented before joint marketing.</p></article></div><div className="heroActions"><a className="primaryButton" href="/joint-venture">Submit your JV deal</a><a className="secondaryButton" href="/buyers">Join as a cash buyer</a></div></section>
  <section className="publicSection"><span className="sectionEyebrow">HOW WE OPERATE</span><h2>Simple outside. Controlled inside.</h2><div className="processGrid"><article className="processCard"><span className="processNumber">01 · INTAKE</span><h3>Capture the facts</h3><p>We collect only the information needed to route and evaluate the opportunity.</p></article><article className="processCard"><span className="processNumber">02 · REVIEW</span><h3>Verify before acting</h3><p>Property, buyer, title, and transaction claims remain unverified until reviewed through the operating system.</p></article><article className="processCard"><span className="processNumber">03 · EXECUTION</span><h3>Move with clear gates</h3><p>Qualified opportunities advance to underwriting, negotiation, title, disposition, and closing under controlled workflows.</p></article></div><div className="trustStrip"><div><strong>As-is evaluation</strong><span>Property owners can submit without preparing a retail listing.</span></div><div><strong>Cash-buyer matching</strong><span>Buying boxes are stored for deal matching after intake.</span></div><div><strong>JV control gates</strong><span>Submission does not create marketing authority or compensation rights.</span></div><div><strong>Private operations</strong><span>Internal leads, financials, title records, and controls stay authenticated.</span></div></div></section>
  <footer className="publicFooter"><span>© 2026 SAHJONY CAPITAL LLC. Real estate investment operations.</span><span><a className="backLink" href="/joint-venture">Joint Venture</a> · <a className="backLink" href="/contact">Contact</a> · <a className="backLink" href="/owner-access">Secure Owner Access</a></span></footer>
</main>}