'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const SESSION='sahjony_owner_session';
const SIGN_IN='/login?returnTo=/owner/properties';
type PropertySummary={property_id:number;seller_name?:string;status:string;address:string;city:string;state:string;zip_code:string;arv?:number;repairs?:number;mao?:number;deal_id?:number;deal_stage?:string;projected_assignment_fee?:number};
type Workspace={property:Record<string,any>;seller:Record<string,any>;deal?:Record<string,any>|null;decision?:Record<string,any>;timeline:any[];follow_ups:any[];offers:any[];closing:any[];approvals:any[];buyer_matches:any[];governance:Record<string,boolean>};
function money(value?:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value||0)}

export default function PropertyWorkspaces(){
 const[items,setItems]=useState<PropertySummary[]>([]),[selected,setSelected]=useState<Workspace|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
 const[form,setForm]=useState({arv:'',repairs:'',assignment_fee:'15000',mao_factor:'0.70',confidence:'0.70',source:'owner_underwriting',motivation_score:'',distress_score:'',equity_score:''});
 const request=useCallback(async(path:string,options:RequestInit={})=>{const token=localStorage.getItem(SESSION)||'';if(!token){location.replace(SIGN_IN);throw new Error('Owner session required')}const response=await fetch(`/api/backend${path}`,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(response.status===401||response.status===403){localStorage.removeItem(SESSION);location.replace(SIGN_IN);throw new Error('Owner session expired')}if(!response.ok)throw new Error(body.detail||`Request failed (${response.status})`);return body},[]);
 const syncForm=(w:Workspace)=>{setForm(v=>({...v,arv:String(w.property.arv||''),repairs:String(w.property.repairs||''),confidence:String(w.decision?.underwriting?.confidence??0.70),source:w.decision?.underwriting?.source||'owner_underwriting',motivation_score:String(w.seller.motivation_score||''),distress_score:String(w.seller.distress_score||''),equity_score:String(w.seller.equity_score||'')}))};
 const loadList=useCallback(async()=>{setLoading(true);setError('');try{const data=await request('/property-workspace');setItems(Array.isArray(data)?data:[]);if(data?.length){const w=await request(`/property-workspace/${data[0].property_id}`);setSelected(w);syncForm(w)}}catch(e){setError(e instanceof Error?e.message:'Unable to load properties')}finally{setLoading(false)}},[request]);
 useEffect(()=>{void loadList()},[loadList]);
 async function open(id:number){setError('');setNotice('');try{const w=await request(`/property-workspace/${id}`);setSelected(w);syncForm(w)}catch(e){setError(e instanceof Error?e.message:'Unable to load property')}}
 async function saveUnderwriting(e:FormEvent){e.preventDefault();if(!selected)return;setLoading(true);setError('');setNotice('');try{const payload={arv:Number(form.arv),repairs:Number(form.repairs),assignment_fee:Number(form.assignment_fee),mao_factor:Number(form.mao_factor),confidence:Number(form.confidence),source:form.source,motivation_score:form.motivation_score===''?null:Number(form.motivation_score),distress_score:form.distress_score===''?null:Number(form.distress_score),equity_score:form.equity_score===''?null:Number(form.equity_score)};const w=await request(`/property-workspace/${selected.property.id}/underwriting`,{method:'PUT',body:JSON.stringify(payload)});setSelected(w);syncForm(w);setNotice(`Underwriting saved. Explainable MAO: ${money(w.property.mao)}.`);await refreshPortfolio()}catch(e){setError(e instanceof Error?e.message:'Unable to save underwriting')}finally{setLoading(false)}}
 async function refreshPortfolio(){const data=await request('/property-workspace');setItems(Array.isArray(data)?data:[])}
 async function createDeal(){if(!selected)return;setLoading(true);setError('');setNotice('');try{const w=await request(`/property-workspace/${selected.property.id}/create-deal`,{method:'POST',body:JSON.stringify({owner_confirmed:true,confidence:Number(form.confidence),minimum_confidence:0.65,strategy:'assignment'})});setSelected(w);setNotice('Governed deal created. External outreach remains blocked pending owner approval.');await refreshPortfolio()}catch(e){setError(e instanceof Error?e.message:'Unable to create deal')}finally{setLoading(false)}}
 return <main className={styles.page}>
  <header className={styles.header}><div><span className={styles.eyebrow}>CANONICAL OPERATING RECORD</span><h1>Unified Property Workspace</h1><p>Ownership, underwriting, seller activity, buyer matches, offers, approvals, and closing milestones in one workspace.</p></div><div className={styles.actions}><button onClick={()=>void loadList()} disabled={loading}>Refresh</button><a className={styles.linkButton} href="/owner/nationwide-acquisition">Import leads</a></div></header>
  {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}>
   <article className={styles.card}><span className={styles.eyebrow}>PORTFOLIO</span><h2>{items.length} properties</h2><div className={styles.list}>{items.map(item=><button key={item.property_id} onClick={()=>void open(item.property_id)}><span><b>{item.address}</b><small>{item.city}, {item.state} {item.zip_code} · {item.seller_name||'Seller pending'}</small></span><strong>{item.deal_stage||item.status}</strong></button>)}</div></article>
   <article className={styles.card}><span className={styles.eyebrow}>UNDERWRITING</span><h2>{selected?.property?.address||'Select a property'}</h2>{selected&&<div className={styles.metrics}><article><span>ARV</span><strong>{money(selected.property.arv)}</strong></article><article><span>Repairs</span><strong>{money(selected.property.repairs)}</strong></article><article><span>MAO</span><strong>{money(selected.property.mao)}</strong></article><article><span>Assignment</span><strong>{money(selected.deal?.projected_assignment_fee)}</strong></article></div>}<p>{selected?.property?.bedrooms||'—'} bd · {selected?.property?.bathrooms||'—'} ba · {selected?.property?.sqft||'—'} sqft</p></article>
  </section>
  {selected&&<>
   <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>PROPERTY DECISION ENGINE</span><h2>Explainable underwriting</h2></div><strong>{selected.decision?.ready_for_deal?'READY':'INCOMPLETE'}</strong></div><form className={styles.activationForm} onSubmit={saveUnderwriting}><label>ARV<input type="number" min="1" value={form.arv} onChange={e=>setForm({...form,arv:e.target.value})} required/></label><label>Repairs<input type="number" min="0" value={form.repairs} onChange={e=>setForm({...form,repairs:e.target.value})} required/></label><label>Assignment fee<input type="number" min="0" value={form.assignment_fee} onChange={e=>setForm({...form,assignment_fee:e.target.value})}/></label><label>MAO factor<input type="number" min="0.5" max="0.85" step="0.01" value={form.mao_factor} onChange={e=>setForm({...form,mao_factor:e.target.value})}/></label><label>Confidence<input type="number" min="0" max="1" step="0.01" value={form.confidence} onChange={e=>setForm({...form,confidence:e.target.value})}/></label><label>Source<input value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></label><label>Motivation score<input type="number" min="0" max="100" value={form.motivation_score} onChange={e=>setForm({...form,motivation_score:e.target.value})}/></label><label>Distress score<input type="number" min="0" max="100" value={form.distress_score} onChange={e=>setForm({...form,distress_score:e.target.value})}/></label><label>Equity score<input type="number" min="0" max="100" value={form.equity_score} onChange={e=>setForm({...form,equity_score:e.target.value})}/></label><div className={styles.actions}><button type="submit" disabled={loading}>Save underwriting</button><button type="button" onClick={()=>void createDeal()} disabled={loading||!!selected.deal||!selected.decision?.ready_for_deal||Number(form.confidence)<0.65}>Create governed deal</button></div><small>MAO = ARV × factor − repairs − assignment fee. Deal creation is internal; seller outreach remains blocked until explicit approval.</small></form></section>
   <section className={styles.grid}><article className={styles.card}><span className={styles.eyebrow}>SELLER</span><h2>{selected.seller.name||'Unknown seller'}</h2><div className={styles.metrics}><article><span>Motivation</span><strong>{selected.seller.motivation_score||0}</strong></article><article><span>Distress</span><strong>{selected.seller.distress_score||0}</strong></article><article><span>Equity</span><strong>{selected.seller.equity_score||0}</strong></article></div></article><article className={styles.card}><span className={styles.eyebrow}>DEAL CONTROL</span><h2>{selected.deal?`Deal #${selected.deal.id}`:'No deal created'}</h2><p>{selected.deal?.next_action||'Complete underwriting and meet the confidence threshold.'}</p></article></section>
   <section className={styles.grid}><article className={styles.card}><span className={styles.eyebrow}>BUYER INTELLIGENCE</span><h2>{selected.buyer_matches.length} matches</h2><div className={styles.list}>{selected.buyer_matches.map((b:any)=><div key={b.id}><span><b>{b.company||b.name}</b><small>{b.closing_days} day close · POF {b.proof_of_funds_verified?'verified':'pending'}</small></span><strong>{Math.round(b.reliability_score)}%</strong></div>)}</div></article><article className={styles.card}><span className={styles.eyebrow}>APPROVALS & GOVERNANCE</span><h2>{selected.approvals.length} decisions</h2><div className={styles.list}>{selected.approvals.map((a:any)=><div key={a.id}><span><b>{a.action_type}</b><small>{a.summary}</small></span><strong>{a.status}</strong></div>)}{!selected.approvals.length&&<p>No pending approvals.</p>}</div></article></section>
   <section className={styles.grid}><article className={styles.card}><span className={styles.eyebrow}>TIMELINE</span><h2>Seller and deal history</h2><div className={styles.list}>{selected.timeline.map((t:any)=><div key={t.id}><span><b>{t.type}</b><small>{t.summary}</small></span><strong>{new Date(t.created_at).toLocaleDateString()}</strong></div>)}</div></article><article className={styles.card}><span className={styles.eyebrow}>CLOSING</span><h2>{selected.closing.length} milestones</h2><div className={styles.list}>{selected.closing.map((c:any)=><div key={c.id}><span><b>{c.type}</b><small>{c.owner||'Unassigned'}</small></span><strong>{c.status}</strong></div>)}{!selected.closing.length&&<p>Closing has not been initialized.</p>}</div></article></section>
  </>}
 </main>
}
