'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const API = '/api/business-os';
const SESSION = 'sahjony_owner_session';
type Snapshot = {
  period:string;
  plan:{cash_on_hand:number;monthly_revenue_goal:number;monthly_contract_goal:number;monthly_marketing_budget:number;tax_reserve_percent:number};
  scorecard:{recorded_revenue:number;expenses:number;net_operating_cash:number;marketing_spend:number;tax_reserve:number;cash_after_reserve:number;runway_months?:number;contracts_closed:number;projected_pipeline_revenue:number;revenue_goal_progress:number;contract_goal_progress:number;marketing_budget_used:number};
  alerts:Array<{severity:string;message:string}>;
  transactions:Array<{id:number;transaction_type:string;category:string;amount:number;occurred_on:string;vendor?:string;description?:string}>;
  obligations:Array<{id:number;title:string;category:string;amount:number;cadence:string;next_due_on:string;last_paid_on?:string;owner?:string;status:string}>;
  playbooks:Array<{id:number;title:string;category:string;steps:string[]}>;
};
const EMPTY:Snapshot={period:'',plan:{cash_on_hand:0,monthly_revenue_goal:0,monthly_contract_goal:0,monthly_marketing_budget:0,tax_reserve_percent:25},scorecard:{recorded_revenue:0,expenses:0,net_operating_cash:0,marketing_spend:0,tax_reserve:0,cash_after_reserve:0,contracts_closed:0,projected_pipeline_revenue:0,revenue_goal_progress:0,contract_goal_progress:0,marketing_budget_used:0},alerts:[],transactions:[],obligations:[],playbooks:[]};
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value||0);

export default function BusinessOSPage(){
  const [token,setToken]=useState('');const [data,setData]=useState<Snapshot>(EMPTY);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const request=useCallback(async(path:string,options:RequestInit={},override?:string)=>{const active=override||token;if(!active)throw new Error('Owner session required');const response=await fetch(`${API}${path}`,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${active}`,...(options.headers||{})}});const body=await response.json();if(response.status===401||response.status===403){localStorage.removeItem(SESSION);location.replace('/owner-access');throw new Error('Owner session expired');}if(!response.ok)throw new Error(body.detail||`Request failed (${response.status})`);return body;},[token]);
  const load=useCallback(async(override?:string)=>{setLoading(true);setError('');try{setData(await request('/snapshot',{},override));}catch(e){setError(e instanceof Error?e.message:'Unable to load Business OS');}finally{setLoading(false);}},[request]);
  useEffect(()=>{const stored=localStorage.getItem(SESSION)||'';if(!stored){location.replace('/owner-access?returnTo=/owner/business');return;}setToken(stored);void load(stored);},[load]);
  async function submit(path:string,event:FormEvent<HTMLFormElement>,transform:(form:FormData)=>Record<string,unknown>,method='POST'){event.preventDefault();const formElement=event.currentTarget;setLoading(true);setError('');setNotice('');try{await request(path,{method,body:JSON.stringify(transform(new FormData(formElement)))});formElement.reset();setNotice('Business records updated.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to save');}finally{setLoading(false);}}
  async function installPlaybooks(){setLoading(true);try{const result=await request('/playbooks/defaults',{method:'POST',body:'{}'});setNotice(`${result.created} operating playbooks installed.`);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to install playbooks');}finally{setLoading(false);}}
  async function markPaid(id:number){if(!window.confirm('Record this obligation as paid and add its amount to the expense ledger?'))return;setLoading(true);try{await request(`/obligations/${id}`,{method:'PATCH',body:JSON.stringify({status:'paid'})});setNotice('Payment recorded and the next recurring due date was scheduled.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to update obligation');}finally{setLoading(false);}}
  return <main className={styles.page}>
    <header className={styles.header}><div><span className={styles.eyebrow}>OWNER OPERATING SYSTEM</span><h1>Business OS</h1><p>Targets, cash, expenses, obligations, runway, and repeatable operating playbooks in one owner view.</p></div><div className={styles.actions}><button onClick={()=>void load()} disabled={loading}>Refresh</button><a className={styles.linkButton} href="/owner">Command center</a></div></header>
    {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
    <section className={styles.metrics}><article><span>Revenue this month</span><strong>{money(data.scorecard.recorded_revenue)}</strong><small>{data.scorecard.revenue_goal_progress}% of goal</small></article><article><span>Expenses</span><strong>{money(data.scorecard.expenses)}</strong></article><article><span>Net operating cash</span><strong>{money(data.scorecard.net_operating_cash)}</strong></article><article><span>Cash after tax reserve</span><strong>{money(data.scorecard.cash_after_reserve)}</strong></article><article><span>Runway</span><strong>{data.scorecard.runway_months==null?'—':`${data.scorecard.runway_months} mo`}</strong></article><article><span>Contracts closed</span><strong>{data.scorecard.contracts_closed}</strong><small>{data.scorecard.contract_goal_progress}% of goal</small></article><article><span>Pipeline revenue</span><strong>{money(data.scorecard.projected_pipeline_revenue)}</strong></article><article><span>Marketing budget</span><strong>{data.scorecard.marketing_budget_used}%</strong></article></section>
    {data.alerts.length>0&&<section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>OWNER ATTENTION</span><h2>Business alerts</h2></div><strong>{data.alerts.length}</strong></div><div className={styles.list}>{data.alerts.map((item,index)=><div key={`${item.message}-${index}`}><span><b>{item.severity.toUpperCase()}</b><small>{item.message}</small></span></div>)}</div></section>}
    <section className={styles.grid}><article className={styles.card}><h2>Monthly operating plan</h2><form className={styles.activationForm} onSubmit={e=>void submit('/plan',e,f=>({cash_on_hand:Number(f.get('cash_on_hand')),monthly_revenue_goal:Number(f.get('monthly_revenue_goal')),monthly_contract_goal:Number(f.get('monthly_contract_goal')),monthly_marketing_budget:Number(f.get('monthly_marketing_budget')),tax_reserve_percent:Number(f.get('tax_reserve_percent'))}),'PUT')}><label>Cash on hand<input name="cash_on_hand" type="number" min="0" step="0.01" defaultValue={data.plan.cash_on_hand}/></label><label>Revenue goal<input name="monthly_revenue_goal" type="number" min="0" defaultValue={data.plan.monthly_revenue_goal}/></label><label>Closed-contract goal<input name="monthly_contract_goal" type="number" min="1" defaultValue={data.plan.monthly_contract_goal}/></label><label>Marketing budget<input name="monthly_marketing_budget" type="number" min="0" defaultValue={data.plan.monthly_marketing_budget}/></label><label>Tax reserve %<input name="tax_reserve_percent" type="number" min="0" max="100" defaultValue={data.plan.tax_reserve_percent}/></label><button disabled={loading}>Save operating plan</button></form></article>
    <article className={styles.card}><h2>Record income or expense</h2><form className={styles.activationForm} onSubmit={e=>void submit('/transactions',e,f=>({transaction_type:f.get('transaction_type'),category:f.get('category'),amount:Number(f.get('amount')),occurred_on:f.get('occurred_on'),vendor:f.get('vendor'),description:f.get('description')}))}><label>Type<select name="transaction_type"><option value="income">Income</option><option value="expense">Expense</option></select></label><label>Category<select name="category"><option value="assignment_revenue">Assignment revenue</option><option value="marketing">Marketing</option><option value="payroll">Payroll / contractor</option><option value="software">Software</option><option value="legal">Legal / compliance</option><option value="other">Other</option></select></label><label>Amount<input name="amount" type="number" min=".01" step=".01" required/></label><label>Date<input name="occurred_on" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Vendor / payer<input name="vendor"/></label><label>Description<textarea name="description" rows={3}/></label><button disabled={loading}>Record transaction</button></form></article></section>
    <section className={styles.grid}><article className={styles.card}><h2>Recurring obligations</h2><form className={styles.activationForm} onSubmit={e=>void submit('/obligations',e,f=>({title:f.get('title'),category:f.get('category'),amount:Number(f.get('amount')),cadence:f.get('cadence'),next_due_on:f.get('next_due_on'),owner:f.get('owner')}))}><label>Obligation<input name="title" placeholder="CRM subscription, payroll, license…" required/></label><label>Category<input name="category" defaultValue="operations" required/></label><label>Amount<input name="amount" type="number" min="0" step=".01"/></label><label>Cadence<select name="cadence"><option value="monthly">Monthly</option><option value="weekly">Weekly</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option><option value="one_time">One time</option></select></label><label>Next due<input name="next_due_on" type="date" required/></label><label>Owner<input name="owner"/></label><button disabled={loading}>Add obligation</button></form><div className={styles.list}>{data.obligations.map(item=><div key={item.id}><span><b>{item.title}</b><small>{money(item.amount)} · {item.cadence} · due {item.next_due_on} · {item.owner||'unassigned'}</small></span>{item.status==='active'?<button onClick={()=>void markPaid(item.id)} disabled={loading}>Mark paid</button>:<strong>{item.status}</strong>}</div>)}</div></article>
    <article className={styles.card}><div className={styles.cardHeader}><div><h2>Operating playbooks</h2><p>Standardize the work before delegating or automating it.</p></div><button onClick={()=>void installPlaybooks()} disabled={loading}>Install defaults</button></div><div className={styles.list}>{data.playbooks.length?data.playbooks.map(item=><div key={item.id}><span><b>{item.title}</b><small>{item.category}</small><small>{item.steps.map((step,index)=>`${index+1}. ${step}`).join(' · ')}</small></span></div>):<p>No playbooks installed.</p>}</div></article></section>
    <section className={styles.cardWide}><div className={styles.cardHeader}><div><h2>Transaction ledger</h2><p>Manual operating ledger; reconcile it against your accounting system.</p></div><strong>{data.transactions.length}</strong></div><div className={styles.list}>{data.transactions.length?data.transactions.map(item=><div key={item.id}><span><b>{item.category.replaceAll('_',' ')} · {item.vendor||'No vendor'}</b><small>{item.occurred_on} · {item.description||'No description'}</small></span><strong>{item.transaction_type==='expense'?'-':'+'}{money(item.amount)}</strong></div>):<p>No transactions recorded.</p>}</div></section>
  </main>;
}
