'use client';

import Link from 'next/link';
import { ChangeEvent, useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const API='/api/backend/buyer-intake';
const DIRECTORY_API='/api/backend/buyer-directory';
const MATCH_API='/api/backend/buyer-first-acquisition/snapshot';
const SIGN_IN='/login?returnTo=/owner/buyer-intake';

type Preview={total_rows:number;accepted_count:number;duplicate_count:number;rejected_count:number;verified_pof_count:number;accepted:any[];duplicates:any[];rejected:any[]};
type Snapshot={required_columns:string[];optional_columns:string[];max_rows:number;texas_excluded:boolean;imports:any[];status?:string};
type Buyer={id:number;name:string;company?:string|null;buyer_type:string;phone:string;email?:string|null;zip_codes:string[];asset_types:string[];min_price:number;max_price:number;max_rehab:number;closing_days:number;proof_of_funds_verified:boolean;reliability_score:number;response_rate:number};
type Directory={count:number;summary?:{total_buyers:number;localized_buyers:number;national_or_unscoped_buyers:number;proof_of_funds_verified:number;cash_buyer_candidates:number;cash_evidence_confirmed_candidates:number;autonomously_promoted_candidates:number};operating_mode?:{mode:string;strategy:string;scope:string;lead_acquisition_phase:string;pof_policy:string};buyer_intelligence?:{configured_sources:number;states:string[];counties:string[];ready:boolean;error?:string|null};buyers:Buyer[]};
type BuyerMatch={score:number;status:string;buyer_id:number;buyer_name:string;buyer_company?:string|null;proof_of_funds_verified:boolean;closing_days:number;lead_id:number;property_id:number;address:string;city:string;state:string;zip_code:string;property_type:string;match_price?:number|null;repairs?:number|null;arv?:number|null;mao?:number|null;reasons:string[]};
type MatchSnapshot={buyer_count:number;lead_count:number;matches:BuyerMatch[];fast_track_count:number;pof_verified_buyer_matches:number;policy:string};
const empty:Snapshot={required_columns:['name','phone','zip_codes'],optional_columns:[],max_rows:5000,texas_excluded:false,imports:[],status:'setup'};
const emptyMatches:MatchSnapshot={buyer_count:0,lead_count:0,matches:[],fast_track_count:0,pof_verified_buyer_matches:0,policy:'continuous_general_acquisition_plus_buyer_box_fast_lane'};
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value||0);

export default function BuyerIntakePage(){
 const[data,setData]=useState<Snapshot>(empty);const[directory,setDirectory]=useState<Directory>({count:0,buyers:[]});const[matches,setMatches]=useState<MatchSnapshot>(emptyMatches);const[csv,setCsv]=useState('');const[name,setName]=useState('buyer_csv_import');const[preview,setPreview]=useState<Preview|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[notice,setNotice]=useState('');

 const fetchJson=useCallback(async(url:string,options:RequestInit={})=>{
   const r=await fetch(url,{...options,cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}});
   const text=await r.text();let body:any={};if(text){try{body=JSON.parse(text)}catch{body={detail:text}}}
   if(r.status===401||r.status===403){const sr=await fetch('/api/owner-access/session',{cache:'no-store',credentials:'same-origin'});const session=await sr.json().catch(()=>({}));if(!sr.ok||!session.authenticated){window.location.replace(SIGN_IN);throw new Error('Owner session required');}throw new Error('Your owner session is valid, but the Buyer Network service rejected this request. Stay on this page and review System Health if it persists.');}
   if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:`Request failed (${r.status})`);return body;
 },[]);
 const request=useCallback((path:string,options:RequestInit={})=>fetchJson(`${API}/${path}`,options),[fetchJson]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[snapshotResponse,directoryResponse,matchResponse]=await Promise.all([request('snapshot'),fetchJson(DIRECTORY_API),fetchJson(MATCH_API)]);setData(snapshotResponse);setDirectory(directoryResponse);setMatches(matchResponse);}catch(e){setError(e instanceof Error?e.message:'Unable to load buyer network');}finally{setLoading(false);}},[request,fetchJson]);
 useEffect(()=>{void load();},[load]);
 async function fileChanged(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setCsv(await file.text());setName(file.name.replace(/\.csv$/i,'')||'buyer_csv_import');setPreview(null);setNotice(`Loaded ${file.name}. Run preview before import.`);}
 async function runPreview(){setLoading(true);setError('');setNotice('');try{const result=await request('preview',{method:'POST',body:JSON.stringify({csv_text:csv})});setPreview(result);setNotice(`Preview complete: ${result.accepted_count} accepted, ${result.duplicate_count} duplicates, ${result.rejected_count} rejected.`);}catch(e){setError(e instanceof Error?e.message:'Preview failed');}finally{setLoading(false);}}
 async function commit(){if(!preview||preview.accepted_count===0)return;setLoading(true);setError('');setNotice('');try{const result=await request('commit',{method:'POST',body:JSON.stringify({csv_text:csv,source_label:name})});setNotice(`Imported ${result.created_count} buyer(s).`);setPreview(null);setCsv('');await load();}catch(e){setError(e instanceof Error?e.message:'Import failed');}finally{setLoading(false);}}
 const active=data.status!=='setup';const summary=directory.summary;const intelligence=directory.buyer_intelligence;
 return <main className={styles.page}>
  <header className={styles.header}><div><span className={styles.eyebrow}>BUYER NETWORK · PARALLEL ACQUISITION</span><h1>Reverse Deal Buyer Command Center</h1><p>Buyer intelligence and distressed-property acquisition run in parallel. Known buyer ZIPs and buying boxes create a fast lane for deals that can be underwritten and matched quickly.</p></div><div className={styles.actions}><label className={styles.linkButton}>Choose CSV<input hidden type="file" accept=".csv,text/csv" onChange={fileChanged}/></label><button onClick={()=>void runPreview()} disabled={loading||!csv||!active}>Preview</button><button onClick={()=>void commit()} disabled={loading||!preview||preview.accepted_count===0||!active}>Commit import</button><button onClick={()=>void load()} disabled={loading}>Refresh</button><Link className={styles.linkButton} href="/owner/disposition">Disposition</Link><Link className={styles.linkButton} href="/owner">Command</Link></div></header>
  {!active&&<div className={styles.notice}>API status: SETUP. Redeploy the latest backend to activate buyer imports.</div>}
  <div className={styles.notice}>BUYERS FIRST · REVERSE DEALS · PARALLEL SUPPLY — Lead acquisition never pauses. Buyer ZIP, asset type, price, rehab tolerance, closing speed, reliability and verified POF determine fast-track priority.</div>
  {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.metrics}><article><span>Total buyers</span><strong>{summary?.total_buyers??directory.count}</strong></article><article><span>Localized buyers</span><strong>{summary?.localized_buyers??0}</strong></article><article><span>Fast-track deals</span><strong>{matches.fast_track_count}</strong></article><article><span>Buyer-box matches</span><strong>{matches.matches.length}</strong></article><article><span>Verified POF</span><strong>{summary?.proof_of_funds_verified??directory.buyers.filter(b=>b.proof_of_funds_verified).length}</strong></article></section>
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>BUYER-BOX ACQUISITION FAST LANE</span><h2>Deals ranked against real buying boxes</h2></div><strong>{matches.fast_track_count} fast-track</strong></div><p>General acquisition continues nationwide while these matches receive priority. “Fast-track” means underwriting/title/authority verification priority; it does not authorize an offer, contract, or outreach by itself.</p><div className={styles.list}>{matches.matches.slice(0,20).map((match)=><div key={`${match.lead_id}-${match.buyer_id}`}><span><b>{match.city}, {match.state} {match.zip_code} · Lead #{match.lead_id}</b><small>{match.buyer_company||match.buyer_name} · match {Math.round(match.score)}% · {match.proof_of_funds_verified?'POF VERIFIED':'POF PENDING'} · close {match.closing_days} days · {match.property_type||'property'}{match.match_price?` · target ${money(match.match_price)}`:''}{match.repairs!=null?` · rehab ${money(match.repairs)}`:''}<br/>{match.reasons.join(' · ')}</small></span><strong>{match.status==='fast_track_underwriting'?'FAST TRACK':'MATCHED'}</strong></div>)}{matches.matches.length===0&&<p>No current workspace lead matches a stored buyer box yet. Acquisition continues and new leads will be rescored as they enter.</p>}</div></section>
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>AUTONOMOUS BUYER INTELLIGENCE</span><h2>Recorded-deed coverage</h2></div><strong>{intelligence?.configured_sources??0} live sources</strong></div><p>{intelligence?.ready?`Monitoring ${intelligence.states.length} state(s) across ${intelligence.counties.length} configured county source(s).`:'Recorded-deed intelligence is awaiting configured public or authorized county data sources. No cash status will be inferred from a deed alone.'}</p>{intelligence?.error&&<p>{intelligence.error}</p>}<p>Candidate pool: {summary?.cash_buyer_candidates??0} · cash evidence confirmed: {summary?.cash_evidence_confirmed_candidates??0} · autonomously promoted: {summary?.autonomously_promoted_candidates??0}. POF requires documentary verification.</p></section>
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>LIVE BUYER DIRECTORY</span><h2>Cash buyer contacts, buy boxes & POF</h2></div><strong>{directory.count} buyers</strong></div><div className={styles.list}>{directory.buyers.length?directory.buyers.map((buyer)=><div key={buyer.id}><span><b>{buyer.company||buyer.name}</b><small>{buyer.phone ? <><a href={`tel:${buyer.phone}`}>{buyer.phone}</a>{buyer.email?' · ':''}</> : null}{buyer.email?<a href={`mailto:${buyer.email}`}>{buyer.email}</a>:null}<br/>{(buyer.zip_codes||[]).length?`ZIPs ${(buyer.zip_codes||[]).join(', ')}`:'National / market routing required'} · {(buyer.asset_types||[]).join(', ')||'Any asset'} · buy {money(buyer.min_price)}–{money(buyer.max_price)} · rehab ≤ {money(buyer.max_rehab)} · close {buyer.closing_days} days · reliability {Math.round(buyer.reliability_score)}%</small></span><strong>{buyer.proof_of_funds_verified?'POF VERIFIED':'POF PENDING'}</strong></div>):<p>No buyers are attached to this workspace yet.</p>}</div></section>
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>CSV CONTRACT</span><h2>Required columns</h2></div></div><p>{data.required_columns.join(', ')}</p><p>Optional: {data.optional_columns.join(', ')||'email, company, buyer_type, asset_types, min_price, max_price, max_rehab, closing_days, proof_of_funds_verified, reliability_score, response_rate, source'}</p></section>
  {preview&&<section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>DRY RUN</span><h2>Validation results</h2></div><strong>{preview.total_rows} rows</strong></div><div className={styles.list}>{[...preview.rejected,...preview.duplicates].slice(0,50).map((row:any)=><div key={`${row.row_number}-${row.name}`}><span><b>Row {row.row_number} · {row.name||'Unknown'}</b><small>{row.company||'Independent buyer'} · ZIPs {(row.zip_codes||[]).join(', ')} · {(row.errors||[row.reason]).join('; ')}</small></span><strong>{row.errors?'REJECTED':'DUPLICATE'}</strong></div>)}{preview.rejected_count+preview.duplicate_count===0&&<p>All rows passed validation and deduplication.</p>}</div></section>}
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>IMPORT HISTORY</span><h2>Recent buyer imports</h2></div><strong>{data.imports.length}</strong></div><div className={styles.list}>{data.imports.length?data.imports.map((item:any)=><div key={item.id}><span><b>{item.summary}</b><small>{new Date(item.created_at).toLocaleString()} · verified POF {item.metadata?.proof_of_funds_verified||0} · duplicates {item.metadata?.duplicates||0}</small></span><strong>RECORDED</strong></div>):<p>No buyer CSV import has been committed. The live directory above also includes buyers seeded or discovered through governed sources.</p>}</div></section>
 </main>;
}
