'use client';

import { ChangeEvent, useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const API='/api/backend/buyer-intake';
const DIRECTORY_API='/api/backend/buyer-directory';

type Preview={total_rows:number;accepted_count:number;duplicate_count:number;rejected_count:number;verified_pof_count:number;accepted:any[];duplicates:any[];rejected:any[]};
type Snapshot={required_columns:string[];optional_columns:string[];max_rows:number;texas_excluded:boolean;imports:any[];status?:string};
type Buyer={id:number;name:string;company?:string|null;buyer_type:string;phone:string;email?:string|null;zip_codes:string[];asset_types:string[];min_price:number;max_price:number;max_rehab:number;closing_days:number;proof_of_funds_verified:boolean;reliability_score:number;response_rate:number};
type Directory={count:number;buyers:Buyer[]};
const empty:Snapshot={required_columns:['name','phone','zip_codes'],optional_columns:[],max_rows:5000,texas_excluded:false,imports:[],status:'setup'};
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value||0);

export default function BuyerIntakePage(){
 const [token,setToken]=useState('');const [data,setData]=useState<Snapshot>(empty);const [directory,setDirectory]=useState<Directory>({count:0,buyers:[]});const [csv,setCsv]=useState('');const [name,setName]=useState('buyer_csv_import');const [preview,setPreview]=useState<Preview|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const request=useCallback(async(path:string,options:RequestInit={},override?:string)=>{const active=override||token;if(!active){location.replace('/owner-access');throw new Error('Owner session required');}const r=await fetch(`${API}/${path}`,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${active}`,...(options.headers||{})}});const text=await r.text();let body:any={};if(text){try{body=JSON.parse(text)}catch{body={detail:text}}}if(r.status===401||r.status===403){location.replace('/owner-access');throw new Error('Owner session expired');}if(!r.ok)throw new Error(body.detail||`Request failed (${r.status})`);return body;},[token]);
 const load=useCallback(async(override?:string)=>{const active=override||token;setLoading(true);setError('');try{const [snapshotResponse,directoryResponse]=await Promise.all([request('snapshot',{},active),fetch(DIRECTORY_API,{cache:'no-store',headers:{Authorization:`Bearer ${active}`}})]);if(directoryResponse.status===401||directoryResponse.status===403){location.replace('/owner-access');throw new Error('Owner session expired');}if(!directoryResponse.ok)throw new Error(`Buyer directory failed (${directoryResponse.status})`);setData(snapshotResponse);setDirectory(await directoryResponse.json());}catch(e){setError(e instanceof Error?e.message:'Unable to load buyer network');}finally{setLoading(false);}},[request,token]);
 useEffect(()=>{const stored='cookie-session';setToken(stored);void load(stored);},[load]);
 async function fileChanged(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setCsv(await file.text());setName(file.name.replace(/\.csv$/i,'')||'buyer_csv_import');setPreview(null);setNotice(`Loaded ${file.name}. Run preview before import.`);}
 async function runPreview(){setLoading(true);setError('');setNotice('');try{const result=await request('preview',{method:'POST',body:JSON.stringify({csv_text:csv})});setPreview(result);setNotice(`Preview complete: ${result.accepted_count} accepted, ${result.duplicate_count} duplicates, ${result.rejected_count} rejected.`);}catch(e){setError(e instanceof Error?e.message:'Preview failed');}finally{setLoading(false);}}
 async function commit(){if(!preview||preview.accepted_count===0)return;setLoading(true);setError('');setNotice('');try{const result=await request('commit',{method:'POST',body:JSON.stringify({csv_text:csv,source_label:name})});setNotice(`Imported ${result.created_count} buyer(s).`);setPreview(null);setCsv('');await load();}catch(e){setError(e instanceof Error?e.message:'Import failed');}finally{setLoading(false);}}
 const active=data.status!=='setup';
 return <main className={styles.page}>
  <header className={styles.header}><div><span className={styles.eyebrow}>BUYER NETWORK</span><h1>Buyer Network Intake Center</h1><p>Preview, validate, deduplicate, import, and review cash buyers with buying boxes, direct business contacts, and proof-of-funds status.</p></div><div className={styles.actions}><label className={styles.linkButton}>Choose CSV<input hidden type="file" accept=".csv,text/csv" onChange={fileChanged}/></label><button onClick={()=>void runPreview()} disabled={loading||!csv||!active}>Preview</button><button onClick={()=>void commit()} disabled={loading||!preview||preview.accepted_count===0||!active}>Commit import</button><button onClick={()=>void load()} disabled={loading}>Refresh</button><a className={styles.linkButton} href="/owner/disposition">Disposition</a><a className={styles.linkButton} href="/owner">Control Plane</a></div></header>
  {!active&&<div className={styles.notice}>API status: SETUP. Redeploy the latest backend to activate buyer imports.</div>}
  {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.metrics}><article><span>Cash buyers</span><strong>{directory.count}</strong></article><article><span>Verified POF</span><strong>{directory.buyers.filter(b=>b.proof_of_funds_verified).length}</strong></article><article><span>Accepted</span><strong>{preview?.accepted_count||0}</strong></article><article><span>Duplicates</span><strong>{preview?.duplicate_count||0}</strong></article><article><span>Rejected</span><strong>{preview?.rejected_count||0}</strong></article></section>
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>LIVE BUYER DIRECTORY</span><h2>Cash buyer contacts, buy boxes & POF</h2></div><strong>{directory.count} buyers</strong></div><div className={styles.list}>{directory.buyers.length?directory.buyers.map((buyer)=><div key={buyer.id}><span><b>{buyer.company||buyer.name}</b><small>{buyer.phone ? <><a href={`tel:${buyer.phone}`}>{buyer.phone}</a>{buyer.email?' · ':''}</> : null}{buyer.email?<a href={`mailto:${buyer.email}`}>{buyer.email}</a>:null}<br/>ZIPs {(buyer.zip_codes||[]).join(', ')||'Not set'} · {(buyer.asset_types||[]).join(', ')||'Any asset'} · buy {money(buyer.min_price)}–{money(buyer.max_price)} · rehab ≤ {money(buyer.max_rehab)} · close {buyer.closing_days} days · reliability {Math.round(buyer.reliability_score)}%</small></span><strong>{buyer.proof_of_funds_verified?'POF VERIFIED':'POF PENDING'}</strong></div>):<p>No buyers are attached to this workspace yet.</p>}</div></section>
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>CSV CONTRACT</span><h2>Required columns</h2></div></div><p>{data.required_columns.join(', ')}</p><p>Optional: {data.optional_columns.join(', ')||'email, company, buyer_type, asset_types, min_price, max_price, max_rehab, closing_days, proof_of_funds_verified, reliability_score, response_rate, source'}</p></section>
  {preview&&<section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>DRY RUN</span><h2>Validation results</h2></div><strong>{preview.total_rows} rows</strong></div><div className={styles.list}>{[...preview.rejected,...preview.duplicates].slice(0,50).map((row:any)=><div key={`${row.row_number}-${row.name}`}><span><b>Row {row.row_number} · {row.name||'Unknown'}</b><small>{row.company||'Independent buyer'} · ZIPs {(row.zip_codes||[]).join(', ')} · {(row.errors||[row.reason]).join('; ')}</small></span><strong>{row.errors?'REJECTED':'DUPLICATE'}</strong></div>)}{preview.rejected_count+preview.duplicate_count===0&&<p>All rows passed validation and deduplication.</p>}</div></section>}
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>IMPORT HISTORY</span><h2>Recent buyer imports</h2></div><strong>{data.imports.length}</strong></div><div className={styles.list}>{data.imports.length?data.imports.map((item:any)=><div key={item.id}><span><b>{item.summary}</b><small>{new Date(item.created_at).toLocaleString()} · verified POF {item.metadata?.proof_of_funds_verified||0} · duplicates {item.metadata?.duplicates||0}</small></span><strong>RECORDED</strong></div>):<p>No buyer CSV import has been committed.</p>}</div></section>
 </main>;
}
