'use client';
import {useCallback,useEffect,useState} from'react';
import styles from'../owner.module.css';
const SESSION='sahjony_owner_session';
const empty={status:'loading',controls:{},runtime:{active_blocks:0,tracked_buckets:0,rate_limited:0}};
export default function SecurityPage(){
 const[data,setData]=useState<any>(empty),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setError('');const token=localStorage.getItem(SESSION)||'';if(!token){location.replace('/owner-access');return;}try{const r=await fetch('/api/security/snapshot',{cache:'no-store',headers:{Authorization:`Bearer ${token}`}});const b=await r.json().catch(()=>({detail:'Invalid security response'}));if(r.status===401||r.status===403){localStorage.removeItem(SESSION);location.replace('/owner-access');return;}if(!r.ok)throw new Error(b.detail||`Request failed (${r.status})`);setData(b);}catch(e){setError(e instanceof Error?e.message:'Unable to load security status');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);const controls=Object.entries(data.controls||{});
 return <main className={styles.page}><header className={styles.header}><div><span className={styles.eyebrow}>SECURITY OPERATIONS</span><h1>Security Control Center</h1><p>Authentication throttling, response headers, and active runtime blocks.</p></div><div className={styles.actions}><button onClick={()=>void load()} disabled={loading}>{loading?'Checking…':'Refresh'}</button><a className={styles.linkButton} href="/owner/system-health">System Health</a><a className={styles.linkButton} href="/owner">Control Plane</a></div></header>{data.detail&&<div className={styles.notice}>{data.detail}</div>}{error&&<div className={styles.error}>{error}</div>}<section className={styles.metrics}><article><span>Status</span><strong>{String(data.status).toUpperCase()}</strong></article><article><span>Active blocks</span><strong>{data.runtime?.active_blocks||0}</strong></article><article><span>Rate limited</span><strong>{data.runtime?.rate_limited||0}</strong></article><article><span>Tracked buckets</span><strong>{data.runtime?.tracked_buckets||0}</strong></article></section><section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>CONTROLS</span><h2>Protection policy</h2></div><strong>{controls.length}</strong></div><div className={styles.list}>{controls.map(([k,v])=><div key={k}><span><b>{k.replaceAll('_',' ')}</b></span><strong>{String(v)}</strong></div>)}</div></section></main>;
}
