'use client';

import { useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const API='/api/real-estate-intelligence';
const SESSION='sahjony_owner_session';

type Opportunity={property_id:number;lead_id:number;market:string;opportunity_score:number;distress_score:number;equity_score:number;buyer_demand_score:number;data_confidence:number;ownership_verified:boolean;projected_assignment_fee:number|null;reasons:string[];warnings:string[]};
type Snapshot={status:string;providers:Record<string,boolean>;workflow:Record<string,boolean>;summary:Record<string,number>;acquisition_runs:Record<string,number>;opportunities:Opportunity[];detail?:string};
const empty:Snapshot={status:'setup',providers:{},workflow:{},summary:{},acquisition_runs:{},opportunities:[]};
function normalize(value:any):Snapshot{return{status:typeof value?.status==='string'?value.status:'setup',providers:value?.providers&&typeof value.providers==='object'?value.providers:{},workflow:value?.workflow&&typeof value.workflow==='object'?value.workflow:{},summary:value?.summary&&typeof value.summary==='object'?value.summary:{},acquisition_runs:value?.acquisition_runs&&typeof value.acquisition_runs==='object'?value.acquisition_runs:{},opportunities:Array.isArray(value?.opportunities)?value.opportunities:[],detail:typeof value?.detail==='string'?value.detail:undefined};}

export default function RealEstateIntelligencePage(){
 const[token,setToken]=useState('');const[data,setData]=useState<Snapshot>(empty);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const request=useCallback(async(path:string,options:RequestInit={},override?:string)=>{const active=override||token;if(!active){location.replace('/owner-access');throw new Error('Owner session required');}const response=await fetch(`${API}/${path}`,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${active}`,...(options.headers||{})}});const text=await response.text();let body:any={};if(text){try{body=JSON.parse(text)}catch{body={detail:text}}}if(response.status===401||response.status===403){location.replace('/owner-access');throw new Error('Owner session expired');}if(!response.ok)throw new Error(body.detail||`Request failed (${response.status})`);return normalize(body);},[token]);
 const load=useCallback(async(override?:string)=>{setLoading(true);setError('');try{setData(await request('snapshot',{},override));}catch(e){setError(e instanceof Error?e.message:'Unable to load intelligence platform');}finally{setLoading(false);}},[request]);
 useEffect(()=>{const stored='cookie-session';if(!stored){location.replace('/owner-access');return;}setToken(stored);void load(stored);},[load]);
 async function run(){setLoading(true);setError('');setNotice('');try{const response=await fetch(`${API}/run`,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({limit:10})});const text=await response.text();const body=text?JSON.parse(text):{};if(!response.ok)throw new Error(body.detail||`Request failed (${response.status})`);setData(normalize(body.snapshot||body));setNotice(`Pipeline processed ${body.processed||0} lead(s) and scored ${body.intelligence?.properties_scored||0} properties.`);}catch(e){setError(e instanceof Error?e.message:'Pipeline failed');}finally{setLoading(false);}}
 const setup=data.status==='setup';
 return <main className={styles.page}>
  <header className={styles.header}><div><span className={styles.eyebrow}>REAL ESTATE INTELLIGENCE</span><h1>Integrated Intelligence Platform</h1><p>Enrich leads, verify ownership, measure buyer demand, and rank the best wholesale opportunities from one tenant-safe pipeline.</p></div><div className={styles.actions}><button onClick={()=>void run()} disabled={loading||setup}>Run intelligence pipeline</button><button onClick={()=>void load()} disabled={loading}>Refresh</button><a className={styles.linkButton} href="/owner/deal-intelligence">Decision Intelligence</a><a className={styles.linkButton} href="/owner/data-intake">Lead Intake</a><a className={styles.linkButton} href="/owner/buyer-intake">Buyer Intake</a><a className={styles.linkButton} href="/owner">Control Plane</a></div></header>
  {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}{setup&&<div className={styles.notice}>API status: SETUP. Deploy the latest backend to activate the integrated intelligence pipeline.</div>}
  <section className={styles.metrics}><article><span>Leads</span><strong>{data.summary.leads||0}</strong></article><article><span>Scored properties</span><strong>{data.summary.scored_properties||0}</strong></article><article><span>High priority</span><strong>{data.summary.high_priority||0}</strong></article><article><span>Verified buyers</span><strong>{data.summary.verified_buyers||0}</strong></article><article><span>Projected fees</span><strong>${Number(data.summary.projected_assignment_fees||0).toLocaleString()}</strong></article></section>
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>PIPELINE READINESS</span><h2>Providers and workflow</h2></div></div><div className={styles.list}>{Object.entries({...data.providers,...data.workflow}).map(([name,ready])=><div key={name}><span><b>{name.replaceAll('_',' ')}</b><small>{ready?'Operational or available':'Configuration or data required'}</small></span><strong>{ready?'READY':'SETUP'}</strong></div>)}</div></section>
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>RANKED OPPORTUNITIES</span><h2>National opportunity queue</h2></div><strong>{data.opportunities.length}</strong></div><div className={styles.list}>{data.opportunities.length?data.opportunities.map(item=><div key={item.property_id}><span><b>{item.market} · Score {item.opportunity_score}</b><small>Distress {item.distress_score} · Equity {item.equity_score} · Buyer demand {item.buyer_demand_score} · Confidence {item.data_confidence} · Ownership {item.ownership_verified?'verified':'pending'}</small><small>{(item.reasons||[]).join(' · ')||'No positive evidence recorded'}{item.warnings?.length?` · Warnings: ${item.warnings.join('; ')}`:''}</small></span><strong>{item.projected_assignment_fee!=null?`$${Number(item.projected_assignment_fee).toLocaleString()}`:'REVIEW'}</strong></div>):<p>{data.detail||'No properties have been scored yet. Import leads and buyers, then run the pipeline.'}</p>}</div></section>
 </main>;
}
