'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const API='/api/backend/market-land-acquisition';
const ACQ='/api/backend/acquisition-intake';
const SIGN_IN='/login?returnTo=/owner/market-leads';
type Candidate={lead_id:number;property_id?:number;address?:string;city?:string;state?:string;zip_code?:string;source:string;asking_price?:number;created_at:string};
type Readiness={configured:boolean;review_only:boolean;outreach_allowed:boolean;modes:{id:string;label:string;property_type:string}[]};

export default function MarketLeadsPage(){
  const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[ready,setReady]=useState<Readiness|null>(null);const[candidates,setCandidates]=useState<Candidate[]>([]);const[mode,setMode]=useState<'on_market_sfr'|'vacant_land'>('on_market_sfr');const[state,setState]=useState('FL');const[city,setCity]=useState('Pensacola');const[county,setCounty]=useState('');
  const request=useCallback(async(base:string,path:string,options:RequestInit={})=>{const r=await fetch(`${base}${path}`,{...options,cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();let body:any={};if(text){try{body=JSON.parse(text)}catch{body={detail:text}}}if(r.status===401||r.status===403){const sr=await fetch('/api/owner-access/session',{cache:'no-store',credentials:'same-origin'});const session=await sr.json().catch(()=>({}));if(!sr.ok||!session.authenticated){window.location.replace(SIGN_IN);throw new Error('Owner session required');}throw new Error('Your owner session is valid, but Market Leads rejected this request. Stay on this page and review System Health if it persists.');}if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:body.message||`Request failed (${r.status})`);return body},[]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[r,s]=await Promise.all([request(API,'/readiness'),request(ACQ,'/snapshot')]);setReady(r);setCandidates((s.candidates||[]) as Candidate[])}catch(e){setError(e instanceof Error?e.message:'Unable to load market lead desk')}finally{setLoading(false)}},[request]);
  useEffect(()=>{void load()},[load]);
  async function run(e:FormEvent){e.preventDefault();setLoading(true);setError('');setNotice('');try{const body={mode,state:state.trim().toUpperCase(),city:city.trim(),county:county.trim()};const r=await request(API,'/run',{method:'POST',body:JSON.stringify(body)});setNotice(`${mode==='on_market_sfr'?'On-market':'Vacant-land'} search completed in ${r.location}: ${r.created||0} created, ${r.updated||0} updated, ${r.duplicate||0} duplicates, ${r.rejected||0} rejected.`);await load()}catch(e){setError(e instanceof Error?e.message:'Search failed')}finally{setLoading(false)}}
  return <main className={styles.page}>
    <header className={styles.header}><div><span className={styles.eyebrow}>ACQUISITION CHANNELS</span><h1>Market Leads + Vacant Lots</h1><p>Source public on-market motivated listings and vacant land separately from courthouse distress leads. Every candidate remains review-only until evidence and underwriting gates are satisfied.</p></div><div className={styles.actions}><button onClick={()=>void load()} disabled={loading}>Refresh</button><Link className={styles.linkButton} href="/owner/acquisition">Lead Pipeline</Link><Link className={styles.linkButton} href="/owner/owner-resolution">Owner Resolution</Link></div></header>
    {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
    <section className={styles.metrics}><article><span>Search engine</span><strong>{ready?.configured?'READY':'SETUP'}</strong></article><article><span>Channel</span><strong>{mode==='on_market_sfr'?'ON-MARKET':'VACANT LAND'}</strong></article><article><span>Review mode</span><strong>ON</strong></article><article><span>Outreach</span><strong>BLOCKED</strong></article></section>
    <section className={styles.grid}><article className={styles.card}><span className={styles.eyebrow}>CHANNEL</span><h2>Choose acquisition lane</h2><div className={styles.list}><button type="button" onClick={()=>setMode('on_market_sfr')}><span><b>On-Market SFR</b><small>Long DOM · price reductions · as-is · fixer · investor special · public FSBO</small></span></button><button type="button" onClick={()=>setMode('vacant_land')}><span><b>Vacant Lots / Land</b><small>County parcels · tax delinquent land · infill lots · public owner-listed land</small></span></button></div></article><article className={styles.card}><span className={styles.eyebrow}>SEARCH MARKET</span><h2>{mode==='on_market_sfr'?'Motivated listings':'Vacant parcels'}</h2><form className={styles.activationForm} onSubmit={run}><label>State<input value={state} onChange={e=>setState(e.target.value)} maxLength={2} required/></label><label>City<input value={city} onChange={e=>{setCity(e.target.value);if(e.target.value)setCounty('')}} placeholder="Pensacola"/></label><label>County<input value={county} onChange={e=>{setCounty(e.target.value);if(e.target.value)setCity('')}} placeholder="Escambia"/></label><button disabled={loading||!ready?.configured||!state.trim()}>{loading?'Searching…':mode==='on_market_sfr'?'Find On-Market Leads':'Find Vacant Lots'}</button></form></article></section>
    <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>RULES</span><h2>{mode==='on_market_sfr'?'On-market underwriting lane':'Vacant-land underwriting lane'}</h2></div><strong>SEPARATE ECONOMICS</strong></div>{mode==='on_market_sfr'?<div className={styles.list}><div><span><b>Priority</b><small>90+ DOM when evidenced, reductions, as-is, needs repairs, cash-only, estate/fixer/investor language.</small></span></div><div><span><b>Underwriting</b><small>Use verified comps, ARV and rehab. Standard SFR wholesale MAO can be applied after evidence is established.</small></span></div></div>:<div className={styles.list}><div><span><b>Priority</b><small>Residential/infill vacant parcels, tax distress, public owner-listed land and county-supported parcel evidence.</small></span></div><div><span><b>Underwriting</b><small>Do not apply SFR repair logic. Verify zoning/use, access, utilities, dimensions, flood/wetlands, taxes, title and land comps before establishing MAO.</small></span></div></div>}</section>
    <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>PIPELINE</span><h2>Recent property candidates</h2></div><strong>{candidates.length}</strong></div><div className={styles.list}>{candidates.slice(0,50).map(item=><div key={item.lead_id}><span><b>{item.address}, {item.city} {item.state} {item.zip_code}</b><small>Lead #{item.lead_id} · {item.source} · {item.asking_price?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(item.asking_price):'Price not verified'}</small></span><Link className={styles.linkButton} href={`/owner/owner-resolution?lead=${item.lead_id}`}>Resolve owner</Link></div>)}</div></section>
  </main>;
}
