'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const SIGN_IN='/login?returnTo=/owner/phone-os';
type Status={provider:string;inbound_number:string;outbound_number:string;human_transfer_target:string;openai_configured:boolean;bland_configured:boolean;qualification_model:string;operating_mode:string};
type Pipeline={calls:number;qualified:number;hot:number;pending_qualification:number;open_followups:number;human_transfer_target:string;operating_mode:string};
type Call={id:number;lead_id?:number;direction:string;contact:string;status:string;outcome?:string;ai_disclosed:boolean;verbal_opt_out:boolean;qualification?:Record<string,unknown>;created_at:string};

export default function PhoneOsPage(){
  const[status,setStatus]=useState<Status|null>(null);const[pipeline,setPipeline]=useState<Pipeline|null>(null);const[calls,setCalls]=useState<Call[]>([]);const[loading,setLoading]=useState(true);const[notice,setNotice]=useState('');const[error,setError]=useState('');
  const request=useCallback(async(path:string,options:RequestInit={})=>{const r=await fetch(`/api/backend${path}`,{...options,cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(r.status===401||r.status===403){const sr=await fetch('/api/owner-access/session',{cache:'no-store',credentials:'same-origin'});const session=await sr.json().catch(()=>({}));if(!sr.ok||!session.authenticated){window.location.replace(SIGN_IN);throw new Error('Owner session required');}throw new Error('Your owner session is valid, but Seller Conversations rejected this request. Stay on this page and review System Health if it persists.');}if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:`Request failed (${r.status})`);return data},[]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const processed=await request('/phone-os/automation/process-pending',{method:'POST',body:JSON.stringify({limit:10})});const[s,p,c]=await Promise.all([request('/phone-os/status'),request('/phone-os/automation/pipeline'),request('/phone-os/calls')]);setStatus(s);setPipeline(p);setCalls(c||[]);if(processed.processed>0)setNotice(`Phone OS processed ${processed.processed} pending transcript${processed.processed===1?'':'s'}.`)}catch(e){setError(e instanceof Error?e.message:'Unable to load Phone OS')}finally{setLoading(false)}},[request]);
  useEffect(()=>{void load()},[load]);
  async function qualify(id:number){setLoading(true);setError('');setNotice('');try{const r=await request(`/phone-os/calls/${id}/qualify`,{method:'POST',body:'{}'});setNotice(`Call #${id}: ${r.score?.pillars_captured||0}/4 pillars · ${r.score?.hot_lead?'HOT — human handoff':'FOLLOW-UP'}.`);await load()}catch(e){setError(e instanceof Error?e.message:'Qualification failed')}finally{setLoading(false)}}
  return <main className={styles.page}>
    <header className={styles.header}><div><span className={styles.eyebrow}>SAHJONY PHONE OS</span><h1>AI Acquisition Phone System</h1><p>Calls are converted into structured seller intelligence, CRM evidence, supervised follow-up and source-backed acquisition work.</p></div><div className={styles.actions}><button onClick={()=>void load()} disabled={loading}>Process & Refresh</button><Link className={styles.linkButton} href="/owner/communications">Bland Phone System</Link><Link className={styles.linkButton} href="/owner/deal-factory">Leads</Link></div></header>
    {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
    <section className={styles.metrics}><article><span>Provider</span><strong>{status?.provider?.toUpperCase()||'—'}</strong></article><article><span>Inbound AI</span><strong>{status?.inbound_number||'—'}</strong></article><article><span>Outbound</span><strong>{status?.outbound_number||'—'}</strong></article><article><span>Human transfer</span><strong>{status?.human_transfer_target||'—'}</strong></article><article><span>OpenAI</span><strong>{status?.openai_configured?'READY':'SETUP'}</strong></article><article><span>Bland</span><strong>{status?.bland_configured?'READY':'SETUP'}</strong></article></section>
    <section className={styles.metrics}><article><span>Calls</span><strong>{pipeline?.calls??0}</strong></article><article><span>Qualified</span><strong>{pipeline?.qualified??0}</strong></article><article><span>Hot sellers</span><strong>{pipeline?.hot??0}</strong></article><article><span>Pending AI</span><strong>{pipeline?.pending_qualification??0}</strong></article><article><span>Open follow-ups</span><strong>{pipeline?.open_followups??0}</strong></article><article><span>Mode</span><strong>{pipeline?.operating_mode||'supervised'}</strong></article></section>
    <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>OPERATING FLOW</span><h2>Phone → qualification → CRM → acquisition work</h2></div><strong>SUPERVISED</strong></div><div className={styles.list}><div><span><b>1. Capture</b><small>Bland/voice webhooks store call status and transcript with compliance evidence.</small></span></div><div><span><b>2. Auto-qualify</b><small>Phone OS extracts only explicit Motivation, Timeline, Condition and Price statements. Missing facts remain null.</small></span></div><div><span><b>3. Route</b><small>Hot sellers receive priority human review and an acquisition verification job. Non-hot sellers receive a supervised follow-up task.</small></span></div><div><span><b>4. Underwrite</b><small>ARV, ownership, repairs and comps stay source-backed; seller claims never become verified property facts automatically.</small></span></div><div><span><b>5. Execute</b><small>Outbound calls still require compliance + approval. Offers, contracts and money remain human-controlled.</small></span></div></div></section>
    <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>CALL INTELLIGENCE</span><h2>Recent voice calls</h2></div><strong>{calls.length}</strong></div><div className={styles.list}>{calls.length?calls.map(call=><div key={call.id}><span><b>Call #{call.id} · {call.direction} · {call.contact}</b><small>{call.status} · {call.outcome||'no outcome'} · AI disclosed {call.ai_disclosed?'yes':'no'} · opt-out {call.verbal_opt_out?'YES':'no'}</small><small>{call.qualification?`Qualified · ${String(call.qualification.summary||'structured evidence saved')}`:'Pending qualification'}</small></span><span className={styles.decisionButtons}>{!call.qualification&&<button disabled={loading} onClick={()=>void qualify(call.id)}>Qualify now</button>}{call.lead_id&&<Link className={styles.linkButton} href={`/owner/deal-intelligence?lead=${call.lead_id}`}>Underwrite</Link>}</span></div>):<p>No voice calls recorded yet.</p>}</div></section>
  </main>;
}
