'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import AuthShell from '../../components/AuthShell';

export default function ForgotPasswordPage() {
  const [email,setEmail]=useState(''); const [code,setCode]=useState(''); const [password,setPassword]=useState(''); const [confirmPassword,setConfirmPassword]=useState(''); const [step,setStep]=useState<'request'|'reset'>('request'); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function post(action:string,payload:Record<string,string>){const response=await fetch(`/api/owner-access/${action}`,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const text=await response.text();let data:Record<string,unknown>={};try{data=text?JSON.parse(text):{};}catch{throw new Error(`Unreadable response (HTTP ${response.status})`);}if(!response.ok)throw new Error(String(data.detail||`Request failed (HTTP ${response.status})`));return data;}
  async function requestReset(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError('');setMessage('');try{const data=await post('request-password-reset',{email:email.trim().toLowerCase()});setMessage(String(data.message||'A reset code was sent if the account exists.'));setStep('reset');}catch(err){setError(err instanceof Error?err.message:'Unable to request reset.');}finally{setLoading(false);}}
  async function resetPassword(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError('');setMessage('');if(password!==confirmPassword){setError('Passwords do not match.');setLoading(false);return;}try{const data=await post('reset-password',{email:email.trim().toLowerCase(),code,password});setMessage(String(data.message||'Password updated.'));window.setTimeout(()=>{window.location.href='/login';},1200);}catch(err){setError(err instanceof Error?err.message:'Unable to reset password.');}finally{setLoading(false);}}
  return <AuthShell eyebrow="SECURE RECOVERY" title={step==='request'?'Recover access.':'Set a new password.'} description={step==='request'?'Request a time-limited verification code for your authorized owner account.':'Enter the verification code and choose a strong replacement password.'} footer={<><span>Recovery requests never reveal whether an account exists.</span><Link href="/login">Return to sign in</Link></>}>
    {error?<div className="authAlert" role="alert">{error}</div>:null}{message?<div className="authAlert authAlert--success" role="status">{message}</div>:null}
    {step==='request'?<form className="authForm" onSubmit={requestReset}><label htmlFor="reset-email"><span>Executive account email</span><input id="reset-email" type="email" value={email} onChange={event=>setEmail(event.target.value)} autoComplete="username" placeholder="Authorized owner email" required autoFocus /></label><button className="authSubmit" type="submit" disabled={loading}>{loading?'Sending secure code…':'Send reset code'}<span aria-hidden="true">→</span></button></form>:<form className="authForm" onSubmit={resetPassword}><label htmlFor="reset-code"><span>6-digit verification code</span><input id="reset-code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,''))} placeholder="000000" required autoFocus /></label><label htmlFor="new-password"><span>New password</span><input id="new-password" type="password" minLength={12} autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="12 characters minimum" required /></label><label htmlFor="confirm-password"><span>Confirm password</span><input id="confirm-password" type="password" minLength={12} autoComplete="new-password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} placeholder="Repeat your new password" required /></label><button className="authSubmit" type="submit" disabled={loading||code.length!==6}>{loading?'Updating password…':'Update password'}<span aria-hidden="true">→</span></button></form>}
  </AuthShell>;
}
