'use client';

import { ChangeEvent, useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const API='/api/data-intake';
const SESSION='sahjony_owner_session';

type Preview={total_rows:number;accepted_count:number;duplicate_count:number;rejected_count:number;accepted:any[];duplicates:any[];rejected:any[]};
type Snapshot={required_columns:string[];optional_columns:string[];max_rows:number;texas_excluded:boolean;imports:any[];status?:string;detail?:string};
const empty:Snapshot={required_columns:['seller_name','phone','address','city','state','zip_code'],optional_columns:[],max_rows:5000,texas_excluded:true,imports:[],status:'setup'};

export default function DataIntakePage(){
 const [token,setToken]=useState('');const [data,setData]=useState<Snapshot>(empty);const [csv,setCsv]=useState('');const [name,setName]=useState('csv_import');const [preview,setPreview]=useState<Preview|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const request=useCallback(async(path:string,options:RequestInit={},override?:string)=>{const active=override||token;if(!active){location.replace('/owner-access');throw new Error('Owner session required');}const r=await fetch(`${API}/${path}`,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${active}`,...(options.headers||{})}});const text=await r.text();let body:any={};if(text){try{body=JSON.parse(text)}catch{body={detail:text}}}if(r.status===401||r.status===403){location.replace('/owner-access');throw new Error('Owner session expired');}if(!r.ok)throw new Error(body.detail||`Request failed (${r.status})`);return body;},[token]);
 const load=useCallback(async(override?:string)=>{setLoading(true);setError('');try{const result=await request('snapshot',{},override);setData(result);if(result.status==='setup')setNotice(result.detail||'Deploy the latest backend to activate CSV preview and import.');}catch(e){setError(e instanceof Error?e.message:'Unable to load intake center');}finally{setLoading(false);}},[request]);
 useEffect(()=>{const stored='cookie-session';if(!stored){location.replace('/owner-access');return;}setToken(stored);void load(stored);},[load]);
 async function fileChanged(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setCsv(await file.text());setName(file.name.replace(/\.csv$/i,'')||'csv_import');setPreview(null);setNotice(`Loaded ${file.name}. Run preview before import.`);}
 async function runPreview(){setLoading(true);setError('');setNotice('');try{const result=await request('preview',{method:'POST',body:JSON.stringify({csv_text:csv})});setPreview(result);setNotice(`Preview complete: ${result.accepted_count} accepted, ${result.duplicate_count} duplicates, ${result.rejected_count} rejected.`);}catch(e){setError(e instanceof Error?e.message:'Preview failed');}finally{setLoading(false);}}
 async function commit(){if(!preview||preview.accepted_count===0)return;setLoading(true);setError('');setNotice('');try{const result=await request('commit',{method:'POST',body:JSON.stringify({csv_text:csv,source_label:name})});setNotice(`Imported ${result.created_count} lead(s).`);setPreview(null);setCsv('');await load();}catch(e){setError(e instanceof Error?e.message:'Import failed');}finally{setLoading(false);}}
 const setup=data.status==='setup';
 return <main className={styles.page}>
  <header className={styles.header}><div><span className={styles.eyebrow}>PRODUCTION DATA</span><h1>Data Intake Center</h1><p>Preview, validate, deduplicate, and import real lead lists with source provenance and Texas exclusion.</p></div><div className={styles.actions}><label className={styles.linkButton}>Choose CSV<input hidden type="file" accept=".csv,text/csv" onChange={fileChanged}/></label><button onClick={()=>void runPreview()} disabled={loading||!csv||setup}>Preview</button><button onClick={()=>void commit()} disabled={loading||!preview||preview.accepted_count===0||setup}>Commit import</button><button onClick={()=>void load()} disabled={loading}>Refresh</button><a className={styles.linkButton} href="/owner/go-live">Go-Live</a><a className={styles.linkButton} href="/owner">Control Plane</a></div></header>
  {setup&&<div className={styles.notice}><strong>Backend setup required.</strong> {data.detail||'Redeploy the latest backend to activate imports.'}</div>}
  {notice&&!setup&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.metrics}><article><span>API status</span><strong>{setup?'SETUP':'ACTIVE'}</strong></article><article><span>Row limit</span><strong>{data.max_rows}</strong></article><article><span>Accepted</span><strong>{preview?.accepted_count||0}</strong></article><article><span>Duplicates</span><strong>{preview?.duplicate_count||0}</strong></article><article><span>Rejected</span><strong>{preview?.rejected_count||0}</strong></article><article><span>Texas excluded</span><strong>{data.texas_excluded?'YES':'NO'}</strong></article></section>
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>CSV CONTRACT</span><h2>Required columns</h2></div></div><p>{data.required_columns.join(', ')}</p><p>Optional: {data.optional_columns.join(', ')||'email, source, notes, asking_price, arv, repairs, bedrooms, bathrooms, sqft, scoring fields'}</p></section>
  {preview&&<section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>DRY RUN</span><h2>Validation results</h2></div><strong>{preview.total_rows} rows</strong></div><div className={styles.list}>{[...preview.rejected,...preview.duplicates].slice(0,50).map((row:any)=><div key={`${row.row_number}-${row.address}`}><span><b>Row {row.row_number} · {row.seller_name||'Unknown'}</b><small>{row.address}, {row.city} {row.state} {row.zip_code} · {(row.errors||[row.reason]).join('; ')}</small></span><strong>{row.errors?'REJECTED':'DUPLICATE'}</strong></div>)}{preview.rejected_count+preview.duplicate_count===0&&<p>All rows passed validation and deduplication.</p>}</div></section>}
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>IMPORT HISTORY</span><h2>Recent production imports</h2></div><strong>{data.imports.length}</strong></div><div className={styles.list}>{data.imports.length?data.imports.map((item:any)=><div key={item.id}><span><b>{item.summary}</b><small>{new Date(item.created_at).toLocaleString()} · duplicates {item.metadata?.duplicates||0} · rejected {item.metadata?.rejected||0}</small></span><strong>RECORDED</strong></div>):<p>{setup?'Deploy the data-intake backend to load import history.':'No production CSV import has been committed.'}</p>}</div></section>
 </main>;
}
