'use client';

import { useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const SESSION='sahjony_owner_session';
type Provider={id:string;name:string;priority:number;public:boolean;configured:boolean;verified:boolean;state:string;missing:string[];capabilities:string[];truth:string[];verification?:{http_status?:number;reason?:string|null}|null};
type Snapshot={version:string;ready_count:number;provider_count:number;providers:Provider[];orchestration:Record<string,unknown>;safety:Record<string,boolean>};
type RunResult={processed_count:number;committed_count:number;skipped_count:number;commit:boolean;results:Array<{property_id:number;status:string;address?:string;reason?:string;canonical?:Record<string,any>;providers_used?:string[];confidence?:number}>;truth_contract:Record<string,boolean>};

const stateLabel=(state:string)=>state.replaceAll('_',' ').toUpperCase();

export default function LiveDataControlPlane(){
  const [data,setData]=useState<Snapshot|null>(null);const [result,setResult]=useState<RunResult|null>(null);
  const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const request=useCallback(async(path:string,options:RequestInit={})=>{const token=localStorage.getItem(SESSION)||'';if(!token){location.replace('/login?returnTo=/owner/live-data');throw new Error('Owner session required');}const response=await fetch(`/api/provider-intelligence${path}`,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(response.status===401||response.status===403){localStorage.removeItem(SESSION);location.replace('/login?returnTo=/owner/live-data');throw new Error('Owner session expired');}if(!response.ok)throw new Error(body.detail||`Request failed (${response.status})`);return body;},[]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await request('/snapshot'));}catch(e){setError(e instanceof Error?e.message:'Unable to load Provider Intelligence');}finally{setLoading(false);}},[request]);
  useEffect(()=>{void load();},[load]);
  async function verify(providerId:string){setLoading(true);setError('');setNotice('');try{const response=await request('/verify',{method:'POST',body:JSON.stringify({provider_id:providerId})});const provider=response.provider as Provider;setNotice(`${provider.name}: ${stateLabel(provider.state)}${provider.verification?.http_status?` (HTTP ${provider.verification.http_status})`:''}`);await load();}catch(e){setError(e instanceof Error?e.message:'Provider verification failed');}finally{setLoading(false);}}
  async function run(commit:boolean){if(commit&&!confirm('Run Provider Intelligence v2 for up to 25 properties and commit verified fields with provenance?'))return;setLoading(true);setError('');setNotice('');try{const next=await request('/orchestrate',{method:'POST',body:JSON.stringify({limit:25,commit})});setResult(next);setNotice(commit?`${next.committed_count} properties enriched and audited.`:`Preview completed for ${next.processed_count} properties.`);}catch(e){setError(e instanceof Error?e.message:'Provider orchestration failed');}finally{setLoading(false);}}
  return <main className={styles.page}>
    <header className={styles.header}><div><span className={styles.eyebrow}>PROVIDER INTELLIGENCE V2</span><h1>Provider Intelligence Layer</h1><p>One orchestrator for public and licensed property sources, with priority, fallback, provenance, confidence, and truth controls.</p></div><div className={styles.actions}><button onClick={()=>void run(false)} disabled={loading}>Preview orchestration</button><button onClick={()=>void run(true)} disabled={loading}>Run controlled enrichment</button><button onClick={()=>void load()} disabled={loading}>Refresh</button><a className={styles.linkButton} href="/owner/provider-activation">Provider activation</a><a className={styles.linkButton} href="/owner/properties">Property workspaces</a></div></header>
    {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
    <section className={styles.metrics}><article><span>Version</span><strong>{data?.version||'2.1'}</strong></article><article><span>Providers verified</span><strong>{data?`${data.ready_count}/${data.provider_count}`:'—'}</strong></article><article><span>Processed</span><strong>{result?.processed_count||0}</strong></article><article><span>Committed</span><strong>{result?.committed_count||0}</strong></article><article><span>Skipped</span><strong>{result?.skipped_count||0}</strong></article></section>
    <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>PROVIDER MESH</span><h2>Priority, readiness, and credential verification</h2></div><strong>{data?.provider_count||0}</strong></div><div className={styles.list}>{data?.providers.map(p=><div key={p.id}><span><b>{p.name}</b><small>Priority {p.priority} · {p.capabilities.join(', ')}{p.missing.length?` · Missing: ${p.missing.join(', ')}`:''}{p.verification?.http_status?` · HTTP ${p.verification.http_status}`:''}{p.verification?.reason?` · ${p.verification.reason}`:''}</small></span><span><strong>{stateLabel(p.state)}</strong>{p.configured&&!p.public&&<button onClick={()=>void verify(p.id)} disabled={loading}>Verify</button>}</span></div>)}{!data&&<p>Loading provider intelligence.</p>}</div></section>
    <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>CANONICAL RESULTS</span><h2>Latest orchestration run</h2></div><strong>{result?.results.length||0}</strong></div><div className={styles.list}>{result?.results.map(row=><div key={row.property_id}><span><b>Property #{row.property_id}</b><small>{row.address||row.reason||'No address'}{row.providers_used?.length?` · ${row.providers_used.join(', ')}`:''}{typeof row.confidence==='number'?` · ${Math.round(row.confidence*100)}% confidence`:''}</small></span><strong>{row.status.toUpperCase()}</strong></div>)}{!result&&<p>No Provider Intelligence run has been performed in this session.</p>}</div></section>
    <div className={styles.notice}>Configured does not mean verified. Licensed providers are counted ready only after a non-destructive authentication check succeeds. Provider Intelligence never exposes credentials or fabricates ownership, contacts, liens, valuation, distress, or repair data.</div>
  </main>;
}
