'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import styles from '../owner.module.css';

type Candidate={lead_id:number;address?:string;city?:string;state?:string;zip_code?:string;source:string};
type OwnerRecord={verified:boolean;status:string;evidence_count:number;evidence:any[];owner_of_record_name?:string|null;owner_mailing_address?:string|null;source_url?:string|null};
type Resolution={evidence_count:number;evidence:any[];cross_verified_phones:string[];cross_verified_emails:string[];max_identity_match_confidence:number;status:string;contact_ready:boolean;outreach_allowed:boolean;note:string};
type Packet={lead_id:number;property_address:string;city:string;state:string;zip_code:string;owner_of_record_name?:string|null;owner_mailing_address?:string|null;identity_status:string;lookup_fields:Record<string,string|null>;manual_assisted_resolvers:Record<string,{label:string;url:string;mode:string}>;people_search_unlocked:boolean;next_step:string;owner_record:OwnerRecord;resolution:Resolution};

const ACQ='/api/backend/acquisition-intake';
const RES='/api/backend/owner-resolution';
const SIGN_IN='/login?returnTo=/owner/owner-resolution';

export default function OwnerResolutionDesk(){
 const[candidates,setCandidates]=useState<Candidate[]>([]);const[selectedLead,setSelectedLead]=useState<number|''>('');const[packet,setPacket]=useState<Packet|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const[recordKind,setRecordKind]=useState('county_assessor');const[recordUrl,setRecordUrl]=useState('');const[ownerName,setOwnerName]=useState('');const[mailingAddress,setMailingAddress]=useState('');const[parcelId,setParcelId]=useState('');const[recordNotes,setRecordNotes]=useState('Owner name is shown on the official property record for this address.');
 const[sourceName,setSourceName]=useState('truepeoplesearch');const[sourceUrl,setSourceUrl]=useState('https://www.truepeoplesearch.com/');const[phone,setPhone]=useState('');const[email,setEmail]=useState('');const[confidence,setConfidence]=useState('85');const[notes,setNotes]=useState('Exact owner name and address matched the verified owner record.');
 const request=useCallback(async(base:string,path:string,options:RequestInit={})=>{const r=await fetch(`${base}${path}`,{...options,cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();let body:any={};if(text){try{body=JSON.parse(text)}catch{body={detail:text}}}if(r.status===401||r.status===403){const sr=await fetch('/api/owner-access/session',{cache:'no-store',credentials:'same-origin'});const session=await sr.json().catch(()=>({}));if(!sr.ok||!session.authenticated){window.location.replace(SIGN_IN);throw new Error('Owner session required');}throw new Error('Your owner session is valid, but Owner Resolution rejected this request. Stay on this page and review System Health if it persists.');}if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:body.message||`Request failed (${r.status})`);return body},[]);
 const loadPacket=useCallback(async(id:number)=>{const body=await request(RES,`/leads/${id}/packet`);setPacket(body);setSelectedLead(id);setOwnerName(body.owner_record?.owner_of_record_name||body.lookup_fields?.name||'');setMailingAddress(body.owner_record?.owner_mailing_address||'')},[request]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const snap=await request(ACQ,'/snapshot');const items=(snap.candidates||[]) as Candidate[];setCandidates(items);const queryLead=Number(new URLSearchParams(window.location.search).get('lead')||0);const initial=(queryLead&&items.some(x=>x.lead_id===queryLead)?queryLead:items[0]?.lead_id)||0;if(initial)await loadPacket(initial)}catch(e){setError(e instanceof Error?e.message:'Unable to load owner resolution desk')}finally{setLoading(false)}},[loadPacket,request]);
 useEffect(()=>{void load()},[load]);
 async function queueAll(){setLoading(true);setError('');try{const r=await request(RES,'/queue-property-candidates',{method:'POST',body:JSON.stringify({limit:500})});setNotice(`${r.queued} owner-resolution tasks queued. Owner-record verification is stage one.`)}catch(e){setError(e instanceof Error?e.message:'Unable to queue candidates')}finally{setLoading(false)}}
 async function verifyOwner(e:FormEvent){e.preventDefault();if(!selectedLead)return;setLoading(true);setError('');try{const body=await request(RES,`/leads/${selectedLead}/owner-record-evidence`,{method:'POST',body:JSON.stringify({source_kind:recordKind,source_url:recordUrl,owner_of_record_name:ownerName,owner_mailing_address:mailingAddress,parcel_id:parcelId,evidence_notes:recordNotes})});setPacket(body);setNotice('Owner-of-record verified. Contact-resolution sources are now unlocked.')}catch(e){setError(e instanceof Error?e.message:'Owner verification failed')}finally{setLoading(false)}}
 async function recordEvidence(e:FormEvent){e.preventDefault();if(!selectedLead)return;setLoading(true);setError('');try{const r=await request(RES,`/leads/${selectedLead}/evidence`,{method:'POST',body:JSON.stringify({source_name:sourceName,source_url:sourceUrl,candidate_phone:phone,candidate_email:email,identity_match_confidence:Number(confidence),evidence_notes:notes})});setPacket(prev=>prev?{...prev,resolution:r.resolution}:prev);setNotice(`Evidence recorded. Status: ${String(r.resolution.status).replaceAll('_',' ')}.`);setPhone('');setEmail('')}catch(e){setError(e instanceof Error?e.message:'Unable to record evidence')}finally{setLoading(false)}}
 async function applyContact(){if(!selectedLead)return;setLoading(true);setError('');try{const r=await request(RES,`/leads/${selectedLead}/apply-contact-ready`,{method:'POST',body:'{}'});setNotice(`Applied: ${Object.keys(r.applied||{}).join(', ')||'no empty fields'}. Outreach remains blocked.`);await loadPacket(Number(selectedLead))}catch(e){setError(e instanceof Error?e.message:'Unable to apply contact')}finally{setLoading(false)}}
 function selectSource(v:string){setSourceName(v);setSourceUrl(v==='truepeoplesearch'?'https://www.truepeoplesearch.com/':'https://www.cyberbackgroundchecks.com/')}
 const sourceCount=useMemo(()=>new Set(packet?.resolution?.evidence.map((x:any)=>x.source_name)||[]).size,[packet]);
 return <main className={styles.page}>
  <header className={styles.header}><div><span className={styles.eyebrow}>OWNER INTELLIGENCE</span><h1>Owner Resolution Desk</h1><p>Verify the legal owner first, then resolve contact candidates. People-search evidence cannot bypass the owner-record gate.</p></div><div className={styles.actions}><button onClick={()=>void load()} disabled={loading}>Refresh</button><button onClick={()=>void queueAll()} disabled={loading||!candidates.length}>Queue all</button><Link className={styles.linkButton} href="/owner/acquisition">Lead Pipeline</Link><Link className={styles.linkButton} href="/owner/lead-verification">Lead Verification</Link></div></header>
  {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.metrics}><article><span>Candidates</span><strong>{candidates.length}</strong></article><article><span>Owner record</span><strong>{packet?.owner_record?.verified?'VERIFIED':'REQUIRED'}</strong></article><article><span>Contact status</span><strong>{(packet?.resolution?.status||'unverified').replaceAll('_',' ').toUpperCase()}</strong></article><article><span>Evidence</span><strong>{packet?.resolution?.evidence_count||0}</strong></article><article><span>Sources</span><strong>{sourceCount}/2</strong></article><article><span>Outreach</span><strong>BLOCKED</strong></article></section>
  <section className={styles.grid}><article className={styles.card}><span className={styles.eyebrow}>PROPERTY QUEUE</span><h2>Select property</h2><select value={selectedLead} onChange={e=>void loadPacket(Number(e.target.value))}>{candidates.map(x=><option key={x.lead_id} value={x.lead_id}>#{x.lead_id} · {x.address}, {x.city} {x.state}</option>)}</select><div className={styles.list}>{candidates.slice(0,20).map(x=><div key={x.lead_id}><span><b>{x.address}, {x.city} {x.state} {x.zip_code}</b><small>Lead #{x.lead_id} · {x.source}</small></span><button onClick={()=>void loadPacket(x.lead_id)}>Open</button></div>)}</div></article><article className={styles.card}><span className={styles.eyebrow}>GATE 1</span><h2>Official owner record</h2>{packet?<form className={styles.activationForm} onSubmit={verifyOwner}><label>Official source type<select value={recordKind} onChange={e=>setRecordKind(e.target.value)}><option value="county_assessor">County assessor/appraiser</option><option value="recorder_deed">Recorder / deed</option><option value="county_tax">County tax</option><option value="government_open_data">Government open data</option></select></label><label>Official source URL<input type="url" required value={recordUrl} onChange={e=>setRecordUrl(e.target.value)} placeholder="https://official-source..."/></label><label>Owner of record<input required value={ownerName} onChange={e=>setOwnerName(e.target.value)}/></label><label>Mailing address<input value={mailingAddress} onChange={e=>setMailingAddress(e.target.value)}/></label><label>Parcel / account ID<input value={parcelId} onChange={e=>setParcelId(e.target.value)}/></label><label>Evidence notes<textarea rows={3} required value={recordNotes} onChange={e=>setRecordNotes(e.target.value)}/></label><button disabled={loading}>{packet.owner_record.verified?'Update owner evidence':'Verify owner of record'}</button></form>:<p>Select a property.</p>}</article></section>
  {packet&&<section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>GATE 2</span><h2>Contact resolution</h2><p>{packet.people_search_unlocked?'Owner record verified. Manual-assisted public resolvers are unlocked.':'Locked until official owner-of-record evidence is stored.'}</p></div><strong>{packet.people_search_unlocked?'UNLOCKED':'LOCKED'}</strong></div><div className={styles.actions}>{Object.entries(packet.manual_assisted_resolvers).map(([k,v])=><a key={k} className={styles.linkButton} href={v.url} target="_blank" rel="noreferrer">Open {v.label}</a>)}</div>{packet.owner_record.source_url&&<p>Owner source: <a href={packet.owner_record.source_url} target="_blank" rel="noreferrer">official evidence</a></p>}</section>}
  {packet&&packet.people_search_unlocked&&<section className={styles.grid}><article className={styles.card}><span className={styles.eyebrow}>CONTACT EVIDENCE</span><h2>Record candidate</h2><form className={styles.activationForm} onSubmit={recordEvidence}><label>Source<select value={sourceName} onChange={e=>selectSource(e.target.value)}><option value="truepeoplesearch">TruePeopleSearch</option><option value="cyberbackgroundchecks">CyberBackgroundChecks</option></select></label><label>Source URL<input type="url" required value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Confidence<input type="number" min="0" max="100" value={confidence} onChange={e=>setConfidence(e.target.value)}/></label><label>Evidence notes<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button disabled={loading||(!phone&&!email)}>Record evidence</button></form></article><article className={styles.card}><span className={styles.eyebrow}>GATE 3</span><h2>Cross verification</h2><div className={styles.list}>{packet.resolution.evidence.length?packet.resolution.evidence.map((ev:any)=><div key={ev.activity_id}><span><b>{ev.source_name}</b><small>{ev.candidate_phone||ev.candidate_email} · {Math.round(ev.identity_match_confidence)}%</small><small>{ev.evidence_notes}</small></span><a className={styles.linkButton} href={ev.source_url} target="_blank" rel="noreferrer">Source</a></div>):<p>No contact evidence yet.</p>}</div><button onClick={()=>void applyContact()} disabled={loading||!packet.resolution.contact_ready}>{packet.resolution.contact_ready?'Apply Contact Ready':'Needs owner + 2 matching sources + 80%'}</button><small>Applying contact does not authorize a call or SMS.</small></article></section>}
 </main>;
}
