'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import styles from '../owner.module.css';

const API_URL='/api/backend';
const SIGN_IN='/login?returnTo=/owner/title-companies';
type Partner={id:number;name:string;website?:string;phone?:string;email?:string;states:string[];counties:string[];zip_codes:string[];active:boolean;capabilities:{assignment:string;double_close:string;simultaneous_close:string;transactional_funding_coordination:string;remote_closing:string;e_signing:string};track_record:{investor_closings_observed:number;wholesale_closings_observed:number;avg_title_turnaround_days?:number;avg_closing_days?:number;reliability_score:number;fee_transparency_score:number};evidence:unknown[];last_verified_at?:string};
type Closing={deal:{id:number;strategy:string;stage:string};property:{address?:string;city?:string;state?:string;zip_code?:string};title_order?:{title_company?:string}};
type Match={title_company_id:number;name:string;score:number;eligible:boolean;evidence_status:string;status:string;reasons:string[];components:Record<string,number>;contact:{phone?:string;email?:string;website?:string}};

export default function TitleCompanyIntelligencePage(){
 const[partners,setPartners]=useState<Partner[]>([]);const[closings,setClosings]=useState<Closing[]>([]);const[dealId,setDealId]=useState<number|null>(null);const[matches,setMatches]=useState<Match[]>([]);const[loading,setLoading]=useState(false);const[notice,setNotice]=useState('');const[error,setError]=useState('');
 const selected=useMemo(()=>closings.find(x=>x.deal.id===dealId)||closings[0],[closings,dealId]);
 const request=useCallback(async(path:string,options:RequestInit={})=>{const response=await fetch(`${API_URL}${path}`,{...options,cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(response.status===401||response.status===403){const sr=await fetch('/api/owner-access/session',{cache:'no-store',credentials:'same-origin'});const session=await sr.json().catch(()=>({}));if(!sr.ok||!session.authenticated){window.location.replace(SIGN_IN);throw new Error('Owner session required');}throw new Error('Your owner session is valid, but Title Companies rejected this request. Stay on this page and review System Health if it persists.');}if(!response.ok){const detail=typeof data.detail==='string'?data.detail:(data.detail?.message||`Request failed (${response.status})`);throw new Error(detail);}return data},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[registry,closing]=await Promise.all([request('/title-company-matching/snapshot'),request('/closing-command/snapshot')]);setPartners(registry.partners||[]);setClosings(closing.closings||[]);if(!dealId&&closing.closings?.length)setDealId(closing.closings[0].deal.id)}catch(err){setError(err instanceof Error?err.message:'Unable to load title company intelligence')}finally{setLoading(false)}},[request,dealId]);
 useEffect(()=>{void load()},[load]);
 async function addPartner(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const f=new FormData(form);setLoading(true);setError('');const evidenceUrl=String(f.get('evidence_url')||'').trim();try{await request('/title-company-matching/partners',{method:'POST',body:JSON.stringify({name:f.get('name'),website:f.get('website')||null,phone:f.get('phone')||null,email:f.get('email')||null,states:String(f.get('states')||'').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean),assignment_support:f.get('assignment_support'),double_close_support:f.get('double_close_support'),remote_closing:f.get('remote_closing'),e_signing:f.get('e_signing'),wholesale_closings_observed:Number(f.get('wholesale_closings_observed')||0),investor_closings_observed:Number(f.get('investor_closings_observed')||0),avg_title_turnaround_days:f.get('avg_title_turnaround_days')?Number(f.get('avg_title_turnaround_days')):null,reliability_score:Number(f.get('reliability_score')||50),fee_transparency_score:Number(f.get('fee_transparency_score')||50),evidence:evidenceUrl?[{source:'manual_verification',url:evidenceUrl,recorded_at:new Date().toISOString()}]:[],verified_now:Boolean(evidenceUrl)})});form.reset();setNotice('Title/closing partner saved.');await load()}catch(err){setError(err instanceof Error?err.message:'Unable to save partner')}finally{setLoading(false)}}
 async function rank(){if(!selected)return;setLoading(true);setError('');try{const data=await request(`/title-company-matching/deals/${selected.deal.id}/rank`,{method:'POST',body:JSON.stringify({strategy:selected.deal.strategy})});setMatches(data.matches||[]);setNotice(`Ranked ${data.matches?.length||0} closing partners.`)}catch(err){setError(err instanceof Error?err.message:'Unable to rank closing partners')}finally{setLoading(false)}}
 async function selectPartner(id:number){if(!selected)return;setLoading(true);setError('');try{const data=await request(`/title-company-matching/deals/${selected.deal.id}/select/${id}`,{method:'POST',body:JSON.stringify({strategy:selected.deal.strategy})});setNotice(`${data.title_company} selected for Deal #${selected.deal.id}.`);await load()}catch(err){setError(err instanceof Error?err.message:'Unable to select title company')}finally{setLoading(false)}}
 return <main className={styles.page}>
  <header className={styles.header}><div><span className={styles.eyebrow}>CLOSING INTELLIGENCE</span><h1>Title Company Match Engine</h1><p>Match deals to evidence-verified, wholesale and assignment-capable closing partners by jurisdiction, closing structure, track record, speed and reliability.</p></div><div className={styles.actions}><button onClick={()=>void load()} disabled={loading}>Refresh</button><Link className={styles.linkButton} href="/owner/closing">Closing</Link><Link className={styles.linkButton} href="/owner">Command</Link></div></header>
  {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.metrics}><article><span>Partners</span><strong>{partners.length}</strong></article><article><span>Assignment verified</span><strong>{partners.filter(x=>x.capabilities.assignment==='verified').length}</strong></article><article><span>Double-close verified</span><strong>{partners.filter(x=>x.capabilities.double_close==='verified').length}</strong></article><article><span>Evidence gaps</span><strong>{partners.filter(x=>x.capabilities.assignment!=='verified'&&x.capabilities.double_close!=='verified').length}</strong></article></section>
  <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>DEAL MATCH</span><h2>Rank closing partners</h2></div><button onClick={()=>void rank()} disabled={loading||!selected}>Run match</button></div>{closings.length?<select value={selected?.deal.id||''} onChange={e=>{setDealId(Number(e.target.value));setMatches([])}}>{closings.map(c=><option key={c.deal.id} value={c.deal.id}>Deal #{c.deal.id} · {c.property.city}, {c.property.state} · {c.deal.strategy}</option>)}</select>:<p>No deal is available for closing-partner matching.</p>}{selected&&<p><b>{selected.property.address}</b> · {selected.property.city}, {selected.property.state} {selected.property.zip_code} · Current title: {selected.title_order?.title_company||'not selected'}</p>}<div className={styles.list}>{matches.map(m=><div key={m.title_company_id}><span><b>{m.name} · {m.score.toFixed(1)}</b><small>{m.eligible?'ELIGIBLE':'VERIFY FIRST'} · {m.evidence_status}</small><small>{m.reasons.join(' · ')}</small></span><button onClick={()=>void selectPartner(m.title_company_id)} disabled={loading||!m.eligible}>{m.status==='selected'?'Selected':'Select'}</button></div>)}</div></section>
  <section className={styles.grid}><article className={styles.card}><span className={styles.eyebrow}>REGISTRY</span><h2>Closing partner network</h2><div className={styles.list}>{partners.length?partners.map(p=><div key={p.id}><span><b>{p.name}</b><small>{p.states.join(', ')||'Coverage not set'} · Assignment {p.capabilities.assignment} · Double close {p.capabilities.double_close}</small><small>Wholesale closings {p.track_record.wholesale_closings_observed} · Reliability {p.track_record.reliability_score.toFixed(0)} · Evidence {p.evidence.length}</small></span></div>):<p>No title companies in the registry yet.</p>}</div></article><article className={styles.card}><span className={styles.eyebrow}>ADD / VERIFY</span><h2>Add closing partner</h2><form onSubmit={addPartner} className={styles.activationForm}><input name="name" placeholder="Title / escrow company" required/><input name="states" placeholder="States, e.g. FL, GA" required/><input name="website" placeholder="Website"/><input name="phone" placeholder="Phone"/><input name="email" type="email" placeholder="Email"/><label>Assignment support<select name="assignment_support" defaultValue="unverified"><option value="unverified">Unverified</option><option value="claimed">Claimed</option><option value="verified">Verified</option><option value="unsupported">Unsupported</option></select></label><label>Double-close support<select name="double_close_support" defaultValue="unverified"><option value="unverified">Unverified</option><option value="claimed">Claimed</option><option value="verified">Verified</option><option value="unsupported">Unsupported</option></select></label><label>Remote closing<select name="remote_closing" defaultValue="unverified"><option value="unverified">Unverified</option><option value="claimed">Claimed</option><option value="verified">Verified</option><option value="unsupported">Unsupported</option></select></label><label>E-signing<select name="e_signing" defaultValue="unverified"><option value="unverified">Unverified</option><option value="claimed">Claimed</option><option value="verified">Verified</option><option value="unsupported">Unsupported</option></select></label><input name="wholesale_closings_observed" type="number" min="0" placeholder="Observed wholesale closings"/><input name="investor_closings_observed" type="number" min="0" placeholder="Observed investor closings"/><input name="avg_title_turnaround_days" type="number" min="0" step="0.5" placeholder="Avg title turnaround days"/><input name="reliability_score" type="number" min="0" max="100" defaultValue="50"/><input name="fee_transparency_score" type="number" min="0" max="100" defaultValue="50"/><input name="evidence_url" placeholder="Evidence URL (required for verified status)"/><button disabled={loading}>Save partner</button></form></article></section>
  <section className={styles.cardWide}><span className={styles.eyebrow}>CONTROL</span><h2>Evidence policy</h2><p><b>Verified</b> capabilities can be recommended. Claimed or unverified capabilities remain research candidates. A title company being willing to close an assignment does not determine whether that transaction structure is lawful in the applicable jurisdiction. Human selection is required before the Title Order is updated.</p></section>
 </main>;
}
