'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const API = '/api/backend/acquisition-intake';
const SIGN_IN = '/login?returnTo=/owner/acquisition';

type Batch = { id:number; source:string; status:string; records_received:number; records_created:number; records_updated:number; records_duplicate:number; records_rejected:number; created_at:string };
type Candidate = { lead_id:number; property_id?:number; address?:string; city?:string; state?:string; zip_code?:string; source:string; asking_price?:number; created_at:string };
type AutonomousFeed = {enabled:boolean;configured:boolean;secure:boolean;host?:string|null;source:string;review_only:boolean;outreach_allowed:boolean;provider_mode?:string;auto_configured?:boolean;supports_manual_scope?:boolean;source_priority?:string[]};
type Snapshot = { counts:Record<string,number>; batches:Batch[]; candidates?:Candidate[]; autonomous_feed?:AutonomousFeed };
const SAMPLE = JSON.stringify([{seller_name:'Jane Seller',phone:'',email:'',address:'123 Main St',city:'Pensacola',state:'FL',zip_code:'32501',property_type:'single_family',bedrooms:3,bathrooms:2,sqft:1450,distress_signals:['absentee_owner']}],null,2);

export default function AcquisitionIntakePage(){
  const [data,setData]=useState<Snapshot>({counts:{},batches:[]});
  const [records,setRecords]=useState(SAMPLE); const [source,setSource]=useState('propstream');
  const [pastedAddresses,setPastedAddresses]=useState('');
  const [pastedSource,setPastedSource]=useState('public_address_paste'); const [sourceReference,setSourceReference]=useState('');
  const [scopeMode,setScopeMode]=useState<'nationwide'|'state'|'city'|'county'>('nationwide');
  const [scopeState,setScopeState]=useState(''); const [scopeCity,setScopeCity]=useState(''); const [scopeCounty,setScopeCounty]=useState('');
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState('');

  const request=useCallback(async(path:string,options:RequestInit={})=>{
    const r=await fetch(`${API}${path}`,{...options,cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}});
    const text=await r.text(); let body:any={}; if(text){try{body=JSON.parse(text)}catch{body={detail:text}}}
    if(r.status===401||r.status===403){
      const sr=await fetch('/api/owner-access/session',{cache:'no-store',credentials:'same-origin'}); const session=await sr.json().catch(()=>({}));
      if(!sr.ok||!session.authenticated){window.location.replace(SIGN_IN);throw new Error('Owner session required');}
      throw new Error('Your owner session is valid, but the Lead Pipeline service rejected this request. Stay on this page and review System Health if it persists.');
    }
    if(r.status===404)throw new Error('Lead Pipeline API route is unavailable. Review backend deployment health.');
    if(!r.ok){const detail=typeof body.detail==='string'?body.detail:body.detail?.message||body.message;throw new Error(detail||`Request failed (${r.status})`);} return body;
  },[]);

  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await request('/snapshot'));}catch(e){setError(e instanceof Error?e.message:'Unable to load acquisition intake');}finally{setLoading(false);}},[request]);
  useEffect(()=>{void load();},[load]);

  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');setNotice('');try{const parsed=JSON.parse(records);if(!Array.isArray(parsed))throw new Error('Records JSON must be an array.');const result=await request('/import',{method:'POST',body:JSON.stringify({source,records:parsed})});setNotice(`Batch #${result.batch_id}: ${result.created} created, ${result.updated} updated, ${result.duplicate} duplicates, ${result.rejected} rejected.`);await load();}catch(e){setError(e instanceof Error?e.message:'Import failed');}finally{setLoading(false);}}
  async function pasteAndAnalyze(e:FormEvent){e.preventDefault();setLoading(true);setError('');setNotice('');try{const result=await request('/paste-addresses',{method:'POST',body:JSON.stringify({text:pastedAddresses,source:pastedSource,source_reference:sourceReference})});setNotice(`Verified ${result.verified} addresses. ${result.created} candidates created, ${result.duplicate} duplicates, ${result.rejected_lines?.length||0} rejected. Valuation and outreach remain blocked pending evidence and jurisdiction policy.`);setPastedAddresses('');setSourceReference('');await load();}catch(e){setError(e instanceof Error?e.message:'Address analysis failed');}finally{setLoading(false);}}
  async function runAuthorizedFeed(){setLoading(true);setError('');setNotice('');try{const scope=scopeMode==='nationwide'?undefined:{state:scopeState.trim(),city:scopeMode==='city'?scopeCity.trim():'',county:scopeMode==='county'?scopeCounty.trim():''};const result=await request('/autonomous/run',{method:'POST',body:JSON.stringify(scope?{scope}:{})});const targets=(result.search_targets||[]).map((x:any)=>x.city?`${x.city}, ${x.state}`:x.county?`${x.county} County, ${x.state}`:x.state).join(' · ');setNotice(`Distress discovery completed${targets?` for ${targets}`:''}: ${result.received||0} received, ${result.created||0} candidates created, ${result.updated||0} updated, ${result.duplicate||0} duplicates, ${result.rejected||0} rejected. Owner/deed verification and jurisdiction policy remain required before outreach.`);await load();}catch(e){setError(e instanceof Error?e.message:'Distressed-lead discovery failed');}finally{setLoading(false);}}
  async function deleteCandidate(item:Candidate){if(!window.confirm(`Delete lead #${item.lead_id} for ${item.address||'this property'}? Contact data and queued work will be removed.`))return;const reason=window.prompt('Reason for deletion','No longer an acquisition candidate');if(reason===null)return;setLoading(true);setError('');try{await request(`/leads/${item.lead_id}`,{method:'DELETE',body:JSON.stringify({reason})});setNotice(`Lead #${item.lead_id} deleted and queued work cancelled.`);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to delete lead');}finally{setLoading(false);}}

  const autonomousReady=Boolean(data.autonomous_feed?.enabled&&data.autonomous_feed?.configured&&data.autonomous_feed?.secure);
  const scopedReady=scopeMode==='nationwide'||Boolean(scopeState.trim()&&(scopeMode==='state'||(scopeMode==='city'&&scopeCity.trim())||(scopeMode==='county'&&scopeCounty.trim())));
  return <main className={styles.page}>
    <header className={styles.header}><div><span className={styles.eyebrow}>ACQUISITION ENGINE</span><h1>Lead Intake Center</h1><p>Find source-backed distressed properties, import provider records and keep consequential seller actions behind verification and jurisdiction controls.</p></div><div className={styles.actions}><button onClick={()=>void load()} disabled={loading}>Refresh</button><Link className={styles.linkButton} href="/owner/market-intelligence">Market Intelligence</Link><Link className={styles.linkButton} href="/owner/lead-verification">Lead Verification</Link><Link className={styles.linkButton} href="/owner">Command</Link></div></header>
    {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
    <section className={styles.metrics}><article><span>Discovery</span><strong>{autonomousReady?'READY':'SETUP'}</strong></article><article><span>Completed batches</span><strong>{data.counts.completed||0}</strong></article><article><span>Recent batches</span><strong>{data.batches.length}</strong></article><article><span>Created</span><strong>{data.batches.reduce((n,b)=>n+b.records_created,0)}</strong></article><article><span>Duplicates</span><strong>{data.batches.reduce((n,b)=>n+b.records_duplicate,0)}</strong></article><article><span>Rejected</span><strong>{data.batches.reduce((n,b)=>n+b.records_rejected,0)}</strong></article></section>
    <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>AUTONOMOUS DISCOVERY</span><h2>Public-record distress search</h2><p>OpenAI web search prioritizes county assessor/tax, recorder/deed, code enforcement, tax sale, foreclosure/public notices and government open-data sources. Every candidate must carry a source URL returned by the search.</p></div><strong>{data.autonomous_feed?.provider_mode==='openai_web_public'?'OPENAI WEB + PUBLIC RECORDS':data.autonomous_feed?.host||'NOT CONFIGURED'}</strong></div>
      <div className={styles.list}><div><span><b>Source</b><small>{data.autonomous_feed?.source||'other'} · {data.autonomous_feed?.auto_configured?'auto-configured from existing OpenAI backend key':'configured provider'}</small></span><strong>{data.autonomous_feed?.enabled?'ENABLED':'DISABLED'}</strong></div><div><span><b>Safety mode</b><small>Discovery, owner/deed verification and underwriting are allowed nationwide. Outreach, recordings and offers are controlled by jurisdiction policy and approval gates.</small></span><strong>SUPERVISED</strong></div></div>
      <form className={styles.activationForm} onSubmit={e=>{e.preventDefault();void runAuthorizedFeed();}}><label>Search area<select value={scopeMode} onChange={e=>setScopeMode(e.target.value as any)}><option value="nationwide">Nationwide rotation</option><option value="state">State</option><option value="city">City + State</option><option value="county">County + State</option></select></label>{scopeMode!=='nationwide'&&<label>State<input value={scopeState} onChange={e=>setScopeState(e.target.value)} placeholder="TX or Texas" required /></label>}{scopeMode==='city'&&<label>City<input value={scopeCity} onChange={e=>setScopeCity(e.target.value)} placeholder="Houston" required /></label>}{scopeMode==='county'&&<label>County<input value={scopeCounty} onChange={e=>setScopeCounty(e.target.value)} placeholder="Harris" required /></label>}<button type="submit" disabled={loading||!autonomousReady||!scopedReady}>{loading?'Searching public records…':autonomousReady?'Find distressed leads':'Backend OpenAI configuration required'}</button><small>Texas is open. A Texas candidate follows Texas policy rather than a blanket exclusion. Discovery results remain claims until owner/deed and other evidence gates verify them.</small></form>
    </section>
    <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>PASTE & VERIFY</span><h2>Add public and marketplace properties</h2><p>Paste addresses you are authorized to use. Census verifies location and USGS adds terrain context before a review-only candidate is created.</p></div><strong>UP TO 50</strong></div><form className={styles.activationForm} onSubmit={pasteAndAnalyze}><label>Source<select value={pastedSource} onChange={e=>setPastedSource(e.target.value)}><option value="public_address_paste">Public data / address list</option><option value="facebook">Facebook Marketplace or Group</option><option value="fsbo">FSBO listing</option><option value="other">Other marketplace</option></select></label><label>Source page URL (optional)<input type="url" value={sourceReference} onChange={e=>setSourceReference(e.target.value)} placeholder="https://…" /></label><label>Property addresses<textarea value={pastedAddresses} onChange={e=>setPastedAddresses(e.target.value)} rows={7} required placeholder={'100 Main St, Pensacola, FL 32501\n200 Oak Ave,Houston,TX,77002,185000,https://…'} /></label><button disabled={loading||!pastedAddresses.trim()}>{loading?'Verifying official data…':'Verify and add candidates'}</button><small>Optional CSV columns: address, city, state, ZIP, asking price, source URL. SAHJONY does not log into or scrape private groups. Asking prices remain unverified listing claims; ownership, contacts and ARV remain evidence-gated.</small></form></section>
    <section className={styles.cardWide}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>PROPERTY CANDIDATES</span><h2>Review and manage leads</h2></div><strong>{data.candidates?.length||0}</strong></div><div className={styles.list}>{data.candidates?.length?data.candidates.map(item=><div key={item.lead_id}><span><b>{item.address}, {item.city} {item.state} {item.zip_code}</b><small>Lead #{item.lead_id} · {item.source} · {item.asking_price?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(item.asking_price):'No asking price'}</small></span><span className={styles.decisionButtons}><Link className={styles.linkButton} href={`/owner/owner-resolution?lead=${item.lead_id}`}>Verify owner</Link><button type="button" onClick={()=>void deleteCandidate(item)} disabled={loading}>Delete</button></span></div>):<p>No review-only property candidates.</p>}</div></section>
    <section className={styles.grid}><article className={styles.card}><span className={styles.eyebrow}>IMPORT</span><h2>Provider records</h2><form className={styles.activationForm} onSubmit={submit}><select value={source} onChange={e=>setSource(e.target.value)}><option value="propstream">PropStream</option><option value="batchdata">BatchData</option><option value="attom">ATTOM</option><option value="county">County</option><option value="mls">MLS</option><option value="fsbo">FSBO</option><option value="driving_for_dollars">Driving for Dollars</option><option value="csv">CSV</option></select><textarea value={records} onChange={e=>setRecords(e.target.value)} rows={18}/><button disabled={loading}>Import and start workflow</button><small>All states, including Texas, can enter intake. Jurisdiction-specific controls are applied before outreach and consequential seller actions.</small></form></article>
    <article className={styles.card}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>HISTORY</span><h2>Import batches</h2></div><strong>{data.batches.length}</strong></div><div className={styles.list}>{data.batches.length?data.batches.map(b=><div key={b.id}><span><b>Batch #{b.id} · {b.source}</b><small>{b.status} · received {b.records_received}</small><small>{b.records_created} created · {b.records_updated} updated · {b.records_duplicate} duplicate · {b.records_rejected} rejected</small></span></div>):<p>No acquisition imports yet.</p>}</div></article></section>
  </main>;
}
