'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import styles from '../owner.module.css';

const API = '/api/acquisition-intake';
const SESSION = 'sahjony_owner_session';

type Batch = { id:number; source:string; status:string; records_received:number; records_created:number; records_updated:number; records_duplicate:number; records_rejected:number; created_at:string };
type Snapshot = { counts:Record<string,number>; batches:Batch[] };
const SAMPLE = JSON.stringify([{seller_name:'Jane Seller',phone:'',email:'',address:'123 Main St',city:'Pensacola',state:'FL',zip_code:'32501',property_type:'single_family',bedrooms:3,bathrooms:2,sqft:1450,distress_signals:['absentee_owner']}],null,2);

export default function AcquisitionIntakePage(){
  const [token,setToken]=useState(''); const [data,setData]=useState<Snapshot>({counts:{},batches:[]});
  const [records,setRecords]=useState(SAMPLE); const [source,setSource]=useState('propstream');
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const request=useCallback(async(path:string,options:RequestInit={},override?:string)=>{const active=override||token;if(!active){location.replace('/owner-access');throw new Error('Owner session required');}const r=await fetch(`${API}${path}`,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${active}`,...(options.headers||{})}});const text=await r.text();let body:any={};if(text){try{body=JSON.parse(text)}catch{body={detail:text}}}if(r.status===401||r.status===403){location.replace('/owner-access');throw new Error('Owner session expired');}if(r.status===404)throw new Error('Acquisition Intake API is not deployed on the backend yet. Redeploy the backend from latest main.');if(!r.ok)throw new Error(body.detail||`Request failed (${r.status})`);return body;},[token]);
  const load=useCallback(async(override?:string)=>{setLoading(true);setError('');try{setData(await request('/snapshot',{},override));}catch(e){setError(e instanceof Error?e.message:'Unable to load acquisition intake');}finally{setLoading(false);}},[request]);
  useEffect(()=>{const stored='cookie-session';if(!stored){location.replace('/owner-access');return;}setToken(stored);void load(stored);},[load]);
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');setNotice('');try{const parsed=JSON.parse(records);if(!Array.isArray(parsed))throw new Error('Records JSON must be an array.');const result=await request('/import',{method:'POST',body:JSON.stringify({source,records:parsed})});setNotice(`Batch #${result.batch_id}: ${result.created} created, ${result.updated} updated, ${result.duplicate} duplicates, ${result.rejected} rejected.`);await load();}catch(e){setError(e instanceof Error?e.message:'Import failed');}finally{setLoading(false);}}
  return <main className={styles.page}>
    <header className={styles.header}><div><span className={styles.eyebrow}>ACQUISITION ENGINE</span><h1>Lead Intake Center</h1><p>Import PropStream-ready and provider-neutral lead records with tenant-safe deduplication and automatic AI events.</p></div><div className={styles.actions}><button onClick={()=>void load()} disabled={loading}>Refresh</button><a className={styles.linkButton} href="/owner/intelligence">Intelligence</a><a className={styles.linkButton} href="/owner/events">Events</a><a className={styles.linkButton} href="/owner">Control Plane</a></div></header>
    {notice&&<div className={styles.notice}>{notice}</div>}{error&&<div className={styles.error}>{error}</div>}
    <section className={styles.metrics}><article><span>Completed batches</span><strong>{data.counts.completed||0}</strong></article><article><span>Recent batches</span><strong>{data.batches.length}</strong></article><article><span>Created</span><strong>{data.batches.reduce((n,b)=>n+b.records_created,0)}</strong></article><article><span>Updated</span><strong>{data.batches.reduce((n,b)=>n+b.records_updated,0)}</strong></article><article><span>Duplicates</span><strong>{data.batches.reduce((n,b)=>n+b.records_duplicate,0)}</strong></article><article><span>Rejected</span><strong>{data.batches.reduce((n,b)=>n+b.records_rejected,0)}</strong></article></section>
    <section className={styles.grid}><article className={styles.card}><span className={styles.eyebrow}>IMPORT</span><h2>Provider records</h2><form className={styles.activationForm} onSubmit={submit}><select value={source} onChange={e=>setSource(e.target.value)}><option value="propstream">PropStream</option><option value="batchdata">BatchData</option><option value="attom">ATTOM</option><option value="county">County</option><option value="mls">MLS</option><option value="fsbo">FSBO</option><option value="driving_for_dollars">Driving for Dollars</option><option value="csv">CSV</option></select><textarea value={records} onChange={e=>setRecords(e.target.value)} rows={18}/><button disabled={loading}>Import and start workflow</button><small>Texas records are rejected. Existing workspace properties are reconciled without overwriting populated facts.</small></form></article>
    <article className={styles.card}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>HISTORY</span><h2>Import batches</h2></div><strong>{data.batches.length}</strong></div><div className={styles.list}>{data.batches.length?data.batches.map(b=><div key={b.id}><span><b>Batch #{b.id} · {b.source}</b><small>{b.status} · received {b.records_received}</small><small>{b.records_created} created · {b.records_updated} updated · {b.records_duplicate} duplicate · {b.records_rejected} rejected</small></span></div>):<p>No acquisition imports yet.</p>}</div></article></section>
  </main>;
}
